#!/usr/bin/env python3
# Copyright 2023 Google Sans Flex Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Copies a checkout of the repo to another folder, excluding most of the sources

Copies the contents of positional arg 1 to positional arg 2, excluding:
* `.git`
* `sources/*.{ufo,designspace,fea}`
"""

from argparse import ArgumentParser
from pathlib import Path
import shutil
import os


EXCLUDES = {".git"}
SOURCES_EXCLUDED_EXTENSIONS = {".ufo", ".designspace", ".fea"}

parser = ArgumentParser(add_help=False)
parser.add_argument("source", type=Path)
parser.add_argument("target", type=Path)

args = parser.parse_args()
assert isinstance(args.source, Path)
assert isinstance(args.target, Path)

for src_path in args.source.glob("*"):
    if src_path.name in EXCLUDES:
        print(f"Skipped {src_path.name}")
    elif src_path.name == "sources":
        for sources_path in src_path.glob("*"):
            if sources_path.suffix in SOURCES_EXCLUDED_EXTENSIONS:
                print(f"Skipped {sources_path}")
            else:
                dest_path = args.target / os.sep.join(sources_path.parts[1:])
                dest_path.parent.mkdir(parents=False, exist_ok=True)
                if sources_path.is_file():
                    shutil.copyfile(sources_path, dest_path)
                elif sources_path.is_dir():
                    shutil.copytree(sources_path, dest_path)
                print(f"Copied {sources_path} to {dest_path}")
    else:
        dest_path = args.target / src_path.name
        if src_path.is_file():
            shutil.copyfile(src_path, dest_path)
        elif src_path.is_dir():
            shutil.copytree(src_path, dest_path)
        print(f"Copied {src_path} to {dest_path}")
