#!/bin/bash

set -eu
shopt -s nullglob dotglob

source=$1
target=$2
shift 2
exclude=( "$@" )

include() {
    for item in "${exclude[@]}"; do
        if [ "$1" == "$item" ]; then
            return 1
        fi
    done
    return 0
}

echo "Copying $source to $target, excluding ${exclude[*]}"

echo "::group::copy-exclude"
mkdir -p "$target"
for path in "$source"/*; do
    base=$(basename "$path")

    if include "$base"; then
        cp -R "$path" "$target/$base"
    else
        echo "Skipped $path"
    fi
done
echo "::endgroup::"
