[config]
commit_start = "dd8a2028ad079cb986cf6e605914894687e6eb4d"
commit_end = "origin/it-ad-wip-italic-v1.002"
ufo_finder = { algorithm = "designspace", designspace = "sources/italic/GoogleSansFlex-Italic.designspace" }
cache = true
cache_path = ".burndown-chart-generator-cache.toml"

# Green - design finished and ready for review
# Yellow - in progress
# Red - not started
# Blue - in progress for a future version

[[status]]
name = "Ready for review (drawn)"
plot_color = "#2ecc71"
glyph_type = "drawn"
mark_color = "green"

[[status]]
name = "Ready for review (composite)"
glyph_type = "composite"
plot_color = "#a9eec6"
mark_color = "green"

[[status]]
name = "In progress for v1.000 (drawn)"
plot_color = "#3498db"
glyph_type = "drawn"
mark_color = "blue"

[[status]]
name = "In progress for v1.000 (composite)"
plot_color = "#aac7db"
glyph_type = "composite"
mark_color = "blue"

[[status]]
name = "None of the above (drawn)"
plot_color = "#e74c3c"
glyph_type = "drawn"

[[status]]
name = "None of the above (composite & unknown)"
plot_color = "#e7b4af"

[[milestone]]
name = "Concept"
plot_color = "#1d5c85"
start_date = 2023-05-27
due_date = 2023-06-01
total_glyphs = 12
total_ufos = 127

[[milestone]]
name = "Prototype"
plot_color = "#1d5c85"
starts_from_previous = true
due_date = 2023-06-14
total_glyphs = 42           # len("0123457BDENPRSUWbeqstuwzˆˇ˘˛˜˝HAKOGgnoakv ")
total_ufos = 127

[[milestone]]
name = "Alpha"
plot_color = "#1d5c85"
starts_from_previous = true
due_date = 2023-06-27
total_glyphs = 225
total_ufos = 127

[[milestone]]
name = "Beta"
plot_color = "#1d5c85"
starts_from_previous = true
due_date = 2023-06-27
total_glyphs = 520
total_ufos = 127

[glyph_types]
".notdef" = "drawn"
A = "drawn"
AE = "drawn"
Aacute = "composite"
Abreve = "composite"
Acaron = "composite"
Acircumflex = "composite"
Adieresis = "composite"
Agrave = "composite"
Amacron = "composite"
Aogonek = "composite"
Aring = "composite"
Atilde = "composite"
B = "drawn"
C = "drawn"
Cacute = "composite"
Ccaron = "composite"
Ccedilla = "composite"
Cdotaccent = "composite"
D = "drawn"
Dcaron = "composite"
Dcroat = "composite"
E = "drawn"
Eacute = "composite"
Ecaron = "composite"
Ecircumflex = "composite"
Edieresis = "composite"
Edotaccent = "composite"
Egrave = "composite"
Emacron = "composite"
Eogonek = "composite"
Eth = "composite"
Euro = "drawn"
"Euro.tf" = "composite"
F = "drawn"
G = "drawn"
"G.logo" = "drawn"
"G.super" = "drawn"
Gbreve = "composite"
Gcommaaccent = "composite"
Gdotaccent = "composite"
Germandbls = "drawn"
"Google.logo" = "composite"
Gsuper = "composite"
H = "drawn"
Hbar = "composite"
I = "drawn"
IJ = "composite"
Iacute = "composite"
Icircumflex = "composite"
Idieresis = "composite"
Idotaccent = "composite"
Igrave = "composite"
Imacron = "composite"
Iogonek = "composite"
J = "drawn"
K = "drawn"
Kcommaaccent = "composite"
L = "drawn"
Lacute = "composite"
Lcaron = "composite"
Lcommaaccent = "composite"
Ldot = "composite"
Lslash = "composite"
M = "drawn"
N = "drawn"
Nacute = "composite"
Ncaron = "composite"
Ncommaaccent = "composite"
Ntilde = "composite"
O = "drawn"
OE = "drawn"
Oacute = "composite"
Ocircumflex = "composite"
Odieresis = "composite"
Ograve = "composite"
Ohungarumlaut = "composite"
Omacron = "composite"
Oslash = "drawn"
Otilde = "composite"
P = "drawn"
Q = "composite"
R = "drawn"
Racute = "composite"
Rcaron = "composite"
Rcommaaccent = "composite"
S = "drawn"
Sacute = "composite"
Scaron = "composite"
Scedilla = "composite"
Scommaaccent = "composite"
T = "drawn"
Tcaron = "composite"
Tcedilla = "composite"
Tcommaaccent = "composite"
Thorn = "drawn"
U = "drawn"
Uacute = "composite"
Ubreve = "composite"
Ucircumflex = "composite"
Udieresis = "composite"
Ugrave = "composite"
Uhungarumlaut = "composite"
Umacron = "composite"
Uogonek = "composite"
Uring = "composite"
V = "drawn"
W = "drawn"
Wacute = "composite"
Wcircumflex = "composite"
Wdieresis = "composite"
Wgrave = "composite"
X = "drawn"
Y = "drawn"
Yacute = "composite"
Ycircumflex = "composite"
Ydieresis = "composite"
Ygrave = "composite"
Z = "drawn"
Zacute = "composite"
Zcaron = "composite"
Zdotaccent = "composite"
_copyright-C = "drawn"
_copyright-circle = "drawn"
_dots-divide = "drawn"
_registered-R = "drawn"
"_tail.Q" = "drawn"
a = "drawn"
"a.alt" = "drawn"
aacute = "composite"
"aacute.alt" = "composite"
abreve = "composite"
"abreve.alt" = "composite"
acaron = "composite"
"acaron.alt" = "composite"
acircumflex = "composite"
"acircumflex.alt" = "composite"
acute = "composite"
acutecomb = "drawn"
adieresis = "composite"
"adieresis.alt" = "composite"
ae = "drawn"
"ae.alt" = "drawn"
agrave = "composite"
"agrave.alt" = "composite"
amacron = "composite"
"amacron.alt" = "composite"
ampersand = "drawn"
aogonek = "composite"
"aogonek.alt" = "composite"
approxequal = "composite"
"approxequal.tf" = "composite"
aring = "composite"
"aring.alt" = "composite"
asciicircum = "drawn"
asciitilde = "drawn"
asterisk = "drawn"
at = "drawn"
atilde = "composite"
"atilde.alt" = "composite"
b = "drawn"
backslash = "drawn"
bar = "drawn"
braceleft = "composite"
braceright = "drawn"
bracketleft = "composite"
bracketright = "drawn"
breve = "composite"
brevecomb = "drawn"
brokenbar = "drawn"
bullet = "drawn"
c = "drawn"
cacute = "composite"
caron = "composite"
caroncomb = "drawn"
"caroncomb.alt" = "drawn"
ccaron = "composite"
ccedilla = "composite"
cdotaccent = "composite"
cedilla = "composite"
cedillacomb = "drawn"
cent = "drawn"
"cent.tf" = "composite"
circumflex = "composite"
circumflexcomb = "drawn"
colon = "composite"
"colon.tf" = "composite"
"colon.time" = "composite"
comma = "drawn"
"comma.tf" = "composite"
commaaccentcomb = "drawn"
commaturnedabovecomb = "composite"
copyright = "composite"
currency = "drawn"
"currency.tf" = "composite"
d = "drawn"
dcaron = "composite"
dcroat = "drawn"
degree = "drawn"
dieresis = "composite"
dieresiscomb = "drawn"
divide = "composite"
"divide.tf" = "composite"
dollar = "drawn"
"dollar.tf" = "composite"
dotaccent = "composite"
dotaccentcomb = "drawn"
e = "drawn"
"e.logo" = "drawn"
eacute = "composite"
ecaron = "composite"
ecircumflex = "composite"
edieresis = "composite"
edotaccent = "composite"
egrave = "composite"
eight = "drawn"
"eight.denominator" = "drawn"
"eight.numerator" = "composite"
"eight.sinf" = "composite"
"eight.tf" = "composite"
eightsubscript = "composite"
eightsuperscript = "composite"
emacron = "composite"
emdash = "drawn"
emspace = "composite"
endash = "drawn"
enspace = "composite"
eogonek = "composite"
equal = "composite"
"equal.tf" = "composite"
eth = "drawn"
exclam = "drawn"
exclamdown = "composite"
f = "drawn"
f_b = "composite"
f_f = "composite"
f_f_b = "composite"
f_f_h = "composite"
f_f_i = "composite"
f_f_j = "composite"
f_f_k = "composite"
f_f_l = "composite"
f_f_t = "composite"
f_h = "composite"
f_i = "composite"
f_j = "composite"
f_k = "composite"
f_l = "composite"
f_t = "composite"
five = "drawn"
"five.denominator" = "drawn"
"five.numerator" = "composite"
"five.sinf" = "composite"
"five.tf" = "drawn"
fivesubscript = "composite"
fivesuperscript = "composite"
flig1 = "drawn"
flig2 = "drawn"
flig3 = "drawn"
four = "drawn"
"four.denominator" = "drawn"
"four.numerator" = "composite"
"four.sinf" = "composite"
"four.tf" = "drawn"
fourperemspace = "composite"
foursubscript = "composite"
foursuperior = "composite"
foursuperscript = "composite"
fraction = "drawn"
g = "drawn"
"g.alt" = "drawn"
"g.logo" = "drawn"
gbreve = "composite"
"gbreve.alt" = "composite"
gcommaaccent = "composite"
"gcommaaccent.alt" = "composite"
gdotaccent = "composite"
"gdotaccent.alt" = "composite"
germandbls = "drawn"
grave = "composite"
gravecomb = "drawn"
greater = "composite"
"greater.tf" = "composite"
greaterequal = "composite"
greaterequal-stroke = "drawn"
"greaterequal.tf" = "composite"
guillemetleft = "composite"
guillemetright = "composite"
guilsinglleft = "composite"
guilsinglright = "drawn"
h = "drawn"
hairspace = "composite"
hbar = "drawn"
horizontalelipsis = "composite"
hungarumlaut = "composite"
hungarumlautcomb = "drawn"
hyphen = "drawn"
i = "composite"
iacute = "composite"
icircumflex = "composite"
idieresis = "composite"
idotless = "drawn"
igrave = "composite"
ij = "composite"
imacron = "composite"
iogonek = "composite"
j = "composite"
jdotless = "drawn"
k = "drawn"
kcommaaccent = "composite"
l = "drawn"
"l.logo" = "drawn"
lacute = "composite"
lcaron = "composite"
lcommaaccent = "composite"
ldot = "composite"
less = "drawn"
"less.tf" = "composite"
lessequal = "composite"
"lessequal.tf" = "composite"
logicalnot = "drawn"
"logicalnot.tf" = "composite"
lslash = "composite"
m = "drawn"
macron = "composite"
macroncomb = "drawn"
micro = "composite"
minus = "drawn"
"minus.tf" = "composite"
mu = "drawn"
multiply = "drawn"
"multiply.tf" = "composite"
n = "drawn"
nacute = "composite"
ncaron = "composite"
ncommaaccent = "composite"
nine = "composite"
"nine.denominator" = "composite"
"nine.numerator" = "composite"
"nine.sinf" = "composite"
"nine.tf" = "composite"
ninesubscript = "composite"
ninesuperscript = "composite"
notequal = "composite"
notequal-slash = "drawn"
"notequal.tf" = "composite"
ntilde = "composite"
numbersign = "drawn"
"numbersign.tf" = "composite"
o = "drawn"
"o.logo" = "drawn"
oacute = "composite"
ocircumflex = "composite"
odieresis = "composite"
oe = "drawn"
ogonek = "composite"
ogonekcomb = "drawn"
ograve = "composite"
ohungarumlaut = "composite"
omacron = "composite"
one = "drawn"
"one.denominator" = "drawn"
"one.numerator" = "composite"
"one.sinf" = "composite"
"one.tf" = "drawn"
onehalf = "composite"
onequarter = "composite"
onesubscript = "composite"
onesuperior = "composite"
onesuperscript = "composite"
ordfeminine = "drawn"
ordmasculine = "drawn"
oslash = "drawn"
otilde = "composite"
p = "drawn"
paragraph = "drawn"
parenleft = "composite"
parenright = "drawn"
percent = "composite"
"percent.tf" = "composite"
"percentbar.tf" = "drawn"
period = "drawn"
"period.tf" = "composite"
periodcentered = "composite"
plus = "drawn"
"plus.tf" = "composite"
plusminus = "drawn"
"plusminus.tf" = "composite"
q = "drawn"
question = "drawn"
questiondown = "composite"
quotedbl = "composite"
quotedblbase = "composite"
quotedblleft = "composite"
quotedblright = "composite"
quoteleft = "composite"
quoteright = "composite"
quotesinglbase = "composite"
quotesingle = "drawn"
r = "drawn"
racute = "composite"
rcaron = "composite"
rcommaaccent = "composite"
registered = "composite"
ring = "composite"
ringcomb = "drawn"
s = "drawn"
sacute = "composite"
scaron = "composite"
scedilla = "composite"
scommaaccent = "composite"
section = "drawn"
"section.tf" = "composite"
semicolon = "composite"
"semicolon.tf" = "composite"
seven = "drawn"
"seven.denominator" = "drawn"
"seven.numerator" = "composite"
"seven.sinf" = "composite"
"seven.tf" = "drawn"
sevensubscript = "composite"
sevensuperscript = "composite"
six = "drawn"
"six.denominator" = "drawn"
"six.numerator" = "composite"
"six.sinf" = "composite"
"six.tf" = "composite"
sixperemspace = "composite"
sixsubscript = "composite"
sixsuperscript = "composite"
slash = "drawn"
slashlongcomb = "drawn"
"slashlongcomb.case" = "drawn"
slashshortcomb = "drawn"
"slashshortcomb.case" = "drawn"
softhyphen = "composite"
space = "composite"
"space.tf" = "composite"
sterling = "drawn"
"sterling.tf" = "composite"
"strokelongcomb.case" = "drawn"
strokeshortcomb = "drawn"
"strokeshortcomb.case" = "drawn"
t = "drawn"
t_f = "composite"
t_t = "composite"
tcaron = "composite"
tcedilla = "composite"
tcommaaccent = "composite"
thinspace = "composite"
thorn = "drawn"
three = "drawn"
"three.denominator" = "drawn"
"three.numerator" = "composite"
"three.sinf" = "composite"
"three.tf" = "drawn"
threeperemspace = "composite"
threequarters = "composite"
threesubscript = "composite"
threesuperior = "composite"
threesuperscript = "composite"
tilde = "composite"
tildecomb = "drawn"
tlig = "drawn"
trademark = "drawn"
two = "drawn"
"two.denominator" = "drawn"
"two.numerator" = "composite"
"two.sinf" = "composite"
"two.tf" = "drawn"
twosubscript = "composite"
twosuperior = "composite"
twosuperscript = "composite"
u = "drawn"
uacute = "composite"
ubreve = "composite"
ucircumflex = "composite"
udieresis = "composite"
ugrave = "composite"
uhungarumlaut = "composite"
umacron = "composite"
underscore = "drawn"
uni000D = "composite"
uni00A0 = "composite"
uni25CC = "drawn"
uogonek = "composite"
uring = "composite"
v = "drawn"
w = "drawn"
wacute = "composite"
wcircumflex = "composite"
wdieresis = "composite"
wgrave = "composite"
"wiggle.medium" = "drawn"
x = "drawn"
y = "drawn"
yacute = "composite"
ycircumflex = "composite"
ydieresis = "composite"
yen = "drawn"
"yen.tf" = "composite"
ygrave = "composite"
z = "drawn"
zacute = "composite"
zcaron = "composite"
zdotaccent = "composite"
zero = "drawn"
"zero.denominator" = "drawn"
"zero.dnom.percent" = "drawn"
"zero.numerator" = "composite"
"zero.numr.percent" = "composite"
"zero.sinf" = "composite"
"zero.slash" = "drawn"
"zero.tf" = "composite"
zeroslash = "composite"
"zeroslash.tf" = "composite"
zerosubscript = "composite"
zerosuperscript = "composite"
zerowidthspace = "composite"
