sources:
  - GoogleSansFlex.glyphspackage

familyName: Google Sans Flex

recipe:
  # If you're updating this, please also update the variables at the top of the
  # Makefile! Look for ALL_AXES, VF_NAME, and VF_PATH and make sure they match
  # this (without the leading ../).
  ../fonts/variable/GoogleSansFlex[ROND,opsz,slnt,wdth,wght].ttf:
    - source: GoogleSansFlex.glyphspackage
    - operation: buildVariable
      args: >-
        --keep-overlaps
        --filter FlattenComponentsFilter
        --filter DecomposeTransformedComponentsFilter
    - operation: subspace
      axes: GRAD=drop
    - operation: fix
    # Must be done as a post-processing step if stat is defined per-font,
    # otherwise can be either an operation or postprocess
    - postprocess: buildStat
      args: --src STAT.yaml
