sources:
#  - GSFSquare.designspace
#  - GSFWDTH.designspace
  - GoogleSansFlex.designspace
axisOrder:
  - opsz
  - wdth
  - wght
  - ROND
familyName: Google Sans Flex
# The existing UFO sources are quadratics, so it probably does not make sense
# to build OTFs. Also, Google Sans doesn't build OTFs, so it makes sense to do
# the same for Flex
buildOTF: false

# Outlines are quadratic, don't touch.
reverseOutlineDirection: false
removeOutlineOverlaps: false
