name: 'ufodiff'
description: 'A UFO source file diff tool for collaborative typeface development projects'
inputs:
  subcommand:
    description: 'ufodiff delta subcommand'
    required: true
    default: 'delta'
  compare-against:
    description: 'the branch to compare to'
    required: true
    default: 'main'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.subcommand }}
    - all
    - ${{ format('branch:{0}', inputs.compare-against) }}
