name: Cut workspace fonts
description: Slicing workspace fonts from the main Flex VF

inputs:
  vf-artifact:
    description: The artifact name for the main VF
    required: true

outputs:
  artifact-name:
    description: The artifact name for the workspace fonts
    value: ${{ steps.artifact-name.outputs.artifact-name }}

runs:
  using: composite
  steps:
  - name: Log inputs
    shell: bash
    run: 'echo "vf-artifact: ${{ inputs.vf-artifact }}"'
  - name: Download main VF
    uses: actions/download-artifact@v5
    with:
      name: ${{ inputs.vf-artifact }}
      path: fonts/variable
  - name: Set up uv and enable caching
    uses: astral-sh/setup-uv@v7
    with:
      enable-cache: true
      cache-dependency-glob: |
        requirements*.txt
        requirements*.in
  - name: Slice workspace fonts
    shell: bash
    run: |
      # Prevent font re-building
      touch build.stamp
      make workspace
  - name: Generate archive name
    id: artifact-name
    uses: alpha-tango-kilo/gha-artifact-name@v1
    with:
      repo-name: Google Sans Flex workspace
  - name: Upload workspace and tv fonts
    uses: actions/upload-artifact@v4
    with:
      name: ${{ steps.artifact-name.outputs.artifact-name }}
      path: |
        fonts/workspace
        fonts/tv
      compression-level: 9
      if-no-files-found: error
