name: Cut workspace fonts
description: Slicing workspace fonts from the main Flex VF

inputs:
  vf-artifact:
    description: The artifact name for the main VF
    required: true

outputs:
  artifact-name:
    description: The artifact name for the workspace fonts
    value: ${{ steps.artifact-name.outputs.artifact-name }}

runs:
  using: composite
  steps:
  - name: Log inputs
    shell: bash
    run: 'echo "vf-artifact: ${INPUTS_VF_ARTIFACT}"'
    env:
      INPUTS_VF_ARTIFACT: ${{ inputs.vf-artifact }}
  - name: Download main VF
    uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
    with:
      name: ${{ inputs.vf-artifact }}
      path: fonts/variable
  - name: Slice workspace fonts
    shell: bash
    run: |
      # Prevent font re-building
      touch build.stamp
      make workspace
  - name: Generate archive name
    id: artifact-name
    uses: alpha-tango-kilo/gha-artifact-name@49459760611c4a5cedffa13dfb36ca29ab1fdcfc  # v1.3.0
    with:
      repo-name: Google Sans Flex workspace
  - name: Upload workspace and tv fonts
    uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
    with:
      name: ${{ steps.artifact-name.outputs.artifact-name }}
      path: |
        fonts/workspace
        fonts/tv
      compression-level: 9
      if-no-files-found: error
