#MenuTitle: Set Kerning Groups (Latin)
# -*- coding: utf-8 -*-

from __future__ import print_function, division, unicode_literals
__doc__="""
(GUI) Sets kerning groups. A modified variant of Toshi Omagari's »Set Kerning Groups (Lat-Grk-Cyr)« script.
"""

import vanilla
import GlyphsApp
import re

class SetKernPairs ( object ):
	def __init__( self ):
		# Window 'self.w':
		textY  = 19
		spaceX = 10
		spaceY = 10
		buttonX = 90
		buttonY = 20
		windowWidth  = spaceX*4+buttonX*3
		windowHeight = spaceY*6+textY*2+buttonY
		self.w = vanilla.FloatingWindow(
			( windowWidth, windowHeight ), # default window size
			"Set Kerning Groups", # window title
		)
		self.w.textLower = vanilla.TextBox((spaceX, spaceY, 200, textY), "Lowercase style?", sizeStyle='regular')
		self.w.normalButton = vanilla.Button((spaceX, spaceY*2+textY, buttonX, buttonY), "Normal", sizeStyle='regular', callback=self.SetKernPairsMain )
		self.w.cursiveButton = vanilla.Button((spaceX*2+buttonX, spaceY*2+textY, buttonX, buttonY), "Cursive", sizeStyle='regular', callback=self.SetKernPairsMain )
		self.w.allcapButton = vanilla.Button((spaceX*3+buttonX*2, spaceY*2+textY, buttonX, buttonY), "All Cap", sizeStyle='regular', callback=self.SetKernPairsMain )

		self.w.line = vanilla.HorizontalLine((spaceX, spaceX*4+textY*2, -spaceX, 1))
		self.w.radioButton = vanilla.RadioGroup((spaceX, spaceY*5+textY*2, 300, textY), ["All Glyphs", "Selected Glyphs"], sizeStyle='regular', isVertical=False)

		# Open window and focus on it:
		self.w.open()
		self.w.radioButton.set(0)
		self.w.makeKey()
		


	def SetKernPairsMain( self, sender ):
		try:
			thisFont = Glyphs.font # frontmost font
			groupsUC = {
				"A" : ["A_left", "A_right"],
				"Aacute" : ["A_left", "A_right"],
				"Abreve" : ["A_left", "A_right"],
				"Acaron" : ["A_left", "A_right"],
				"Acircumflex" : ["A_left", "A_right"],
				"Adieresis" : ["A_left", "A_right"],
				"Agrave" : ["A_left", "A_right"],
				"Amacron" : ["A_left", "A_right"],
				"Aogonek" : ["A_left", "A_right"],
				"Aring" : ["A_left", "A_right"],
				"Aringacute" : ["A_left", "A_right"],
				"Atilde" : ["A_left", "A_right"],
				"AE" : ["AE_left", "E_right"],
				"AEacute" : ["AE_left", "E_right"],
				"B" : ["H_left", "B_right"],
				"C" : ["O_left", "C_right"],
				"Cacute" : ["O_left", "C_right"],
				"Ccaron" : ["O_left", "C_right"],
				"Ccedilla" : ["O_left", "C_right"],
				"Ccircumflex" : ["O_left", "C_right"],
				"Cdotaccent" : ["O_left", "C_right"],
				"D" : ["H_left", "O_right"],
				"Eth" : ["H_left", "O_right"],
				"Dcaron" : ["H_left", "O_right"],
				"Dcroat" : ["H_left", "O_right"],
				"E" : ["H_left", "E_right"],
				"Eacute" : ["H_left", "E_right"],
				"Ebreve" : ["H_left", "E_right"],
				"Ecaron" : ["H_left", "E_right"],
				"Ecircumflex" : ["H_left", "E_right"],
				"Edieresis" : ["H_left", "E_right"],
				"Edotaccent" : ["H_left", "E_right"],
				"Egrave" : ["H_left", "E_right"],
				"Emacron" : ["H_left", "E_right"],
				"Eogonek" : ["H_left", "E_right"],
				"F" : ["H_left", "F_right"],
				"G" : ["O_left", "G_right"],
				"Gbreve" : ["O_left", "G_right"],
				"Gcircumflex" : ["O_left", "G_right"],
				"Gcommaaccent" : ["O_left", "G_right"],
				"Gcaron" : ["O_left", "G_right"],
				"Gdotaccent" : ["O_left", "G_right"],
				"Germandbls" : ["germandb_left", "B_right"],
				"H" : ["H_left", "H_right"],
				"Hbar" : ["H_left", "H_right"],
				"Hcircumflex" : ["H_left", "H_right"],
				"I" : ["H_left", "H_right"],
				"IJ" : ["H_left", "J_right"],
				"Iacute" : ["H_left", "H_right"],
				"Ibreve" : ["H_left", "H_right"],
				"Icircumflex" : ["H_left", "H_right"],
				"Idieresis" : ["H_left", "H_right"],
				"Idotaccent" : ["H_left", "H_right"],
				"Igrave" : ["H_left", "H_right"],
				"Imacron" : ["H_left", "H_right"],
				"Iogonek" : ["H_left", "H_right"],
				"Itilde" : ["H_left", "H_right"],
				"J" : ["J_left", "J_right"],
				"Jcircumflex" : ["J_left", "J_right"],
				"K" : ["H_left", "K_right"],
				"Kcommaaccent" : ["H_left", "K_right"],
				"L" : ["H_left", "L_right"],
				"Lacute" : ["H_left", "L_right"],
				"Lcaron" : ["H_left", "Lcaron_right"],
				"Lcommaaccent" : ["H_left", "L_right"],
				"Ldot" : ["H_left", "L_right"],
				"Lslash" : ["L_left", "L_right"],
				"M" : ["H_left", "H_right"],
				"N" : ["H_left", "H_right"],
				"Nacute" : ["H_left", "H_right"],
				"Ncaron" : ["H_left", "H_right"],
				"Ncommaaccent" : ["H_left", "H_right"],
				"Eng" : ["H_left", "H_right"],
				"Ntilde" : ["H_left", "H_right"],
				"O" : ["O_left", "O_right"],
				"Oacute" : ["O_left", "O_right"],
				"Obreve" : ["O_left", "O_right"],
				"Ocircumflex" : ["O_left", "O_right"],
				"Odieresis" : ["O_left", "O_right"],
				"Ograve" : ["O_left", "O_right"],
				"Ohungarumlaut" : ["O_left", "O_right"],
				"Omacron" : ["O_left", "O_right"],
				"Oslash" : ["O_left", "O_right"],
				"Oslashacute" : ["O_left", "O_right"],
				"Otilde" : ["O_left", "O_right"],
				"OE" : ["O_left", "E_right"],
				"P" : ["H_left", "P_right"],
				"Thorn" : ["H_left", "Thorn_right"],
				"Q" : ["O_left", "O_right"],
				"R" : ["H_left", "R_right"],
				"Racute" : ["H_left", "R_right"],
				"Rcaron" : ["H_left", "R_right"],
				"Rcommaaccent" : ["H_left", "R_right"],
				"S" : ["S_left", "S_right"],
				"Sacute" : ["S_left", "S_right"],
				"Scaron" : ["S_left", "S_right"],
				"Scedilla" : ["S_left", "S_right"],
				"Scircumflex" : ["S_left", "S_right"],
				"Scommaaccent" : ["S_left", "S_right"],
				"T" : ["T_left", "T_right"],
				"Tbar" : ["T_left", "T_right"],
				"Tcaron" : ["T_left", "T_right"],
				"Tcedilla" : ["T_left", "T_right"],
				"Tcommaaccent" : ["T_left", "T_right"],
				"U" : ["U_left", "U_right"],
				"Uacute" : ["U_left", "U_right"],
				"Ubreve" : ["U_left", "U_right"],
				"Ucircumflex" : ["U_left", "U_right"],
				"Udieresis" : ["U_left", "U_right"],
				"Ugrave" : ["U_left", "U_right"],
				"Uhungarumlaut" : ["U_left", "U_right"],
				"Umacron" : ["U_left", "U_right"],
				"Uogonek" : ["U_left", "U_right"],
				"Uring" : ["U_left", "U_right"],
				"Utilde" : ["U_left", "U_right"],
				"V" : ["V_left", "V_right"],
				"W" : ["W_left", "W_right"],
				"Wacute" : ["W_left", "W_right"],
				"Wcircumflex" : ["W_left", "W_right"],
				"Wdieresis" : ["W_left", "W_right"],
				"Wgrave" : ["W_left", "W_right"],
				"X" : ["X_left", "X_right"],
				"Y" : ["Y_left", "Y_right"],
				"Yacute" : ["Y_left", "Y_right"],
				"Ycircumflex" : ["Y_left", "Y_right"],
				"Ydieresis" : ["Y_left", "Y_right"],
				"Ygrave" : ["Y_left", "Y_right"],
				"Z" : ["Z_left", "Z_right"],
				"Zacute" : ["Z_left", "Z_right"],
				"Zcaron" : ["Z_left", "Z_right"],
				"Zdotaccent" : ["Z_left", "Z_right"]
			}

			groupsLCnormal = {
				"a" : ["a_left", "a_right"],
				"aacute" : ["a_left", "a_right"],
				"abreve" : ["a_left", "a_right"],
				"acaron" : ["a_left", "a_right"],
				"acircumflex" : ["a_left", "a_right"],
				"adieresis" : ["a_left", "a_right"],
				"agrave" : ["a_left", "a_right"],
				"amacron" : ["a_left", "a_right"],
				"aogonek" : ["a_left", "a_right"],
				"aring" : ["a_left", "a_right"],
				"aringacute" : ["a_left", "a_right"],
				"atilde" : ["a_left", "a_right"],
				"ae" : ["a_left", "e_right"],
				"aeacute" : ["a_left", "e_right"],
				"b" : ["l_left", "bowl_right"],
				"c" : ["o_left", "c_right"],
				"cacute" : ["o_left", "c_right"],
				"ccaron" : ["o_left", "c_right"],
				"ccedilla" : ["o_left", "c_right"],
				"ccircumflex" : ["o_left", "c_right"],
				"cdotaccent" : ["o_left", "c_right"],
				"d" : ["bowl_left", "l_right"],
				"eth" : ["eth_left", "eth_right"],
				"dcaron" : ["bowl_left", "l_right"],
				"dcroat" : ["bowl_left", "l_right"],
				"e" : ["o_left", "e_right"],
				"eacute" : ["o_left", "e_right"],
				"ebreve" : ["o_left", "e_right"],
				"ecaron" : ["o_left", "e_right"],
				"ecircumflex" : ["o_left", "e_right"],
				"edieresis" : ["o_left", "e_right"],
				"edotaccent" : ["o_left", "e_right"],
				"egrave" : ["o_left", "e_right"],
				"emacron" : ["o_left", "e_right"],
				"eogonek" : ["o_left", "e_right"],
				"f" : ["f_left", "f_right"],
				"g" : ["bowl_left", "u_right"],
				"gbreve" : ["bowl_left", "u_right"],
				"gcircumflex" : ["bowl_left", "u_right"],
				"gcommaaccent" : ["bowl_left", "u_right"],
				"gdotaccent" : ["bowl_left", "u_right"],
				"germandbls" : ["germandb_left", "germandb_right"],
				"h" : ["l_left", "n_right"],
				"hbar" : ["l_left", "n_right"],
				"hcircumflex" : ["l_left", "n_right"],
				"i" : ["i_left", "i_right"],
				"dotlessi" : ["n_left", "u_right"],
				"idotless" : ["n_left", "u_right"],
				"iacute" : ["i_left", "i_right"],
				"ibreve" : ["i_left", "i_right"],
				"icircumflex" : ["i_left", "i_right"],
				"idieresis" : ["i_left", "i_right"],
				"idotaccent" : ["i_left", "i_right"],
				"igrave" : ["i_left", "i_right"],
				"ij" : ["i_left", "i_right"],
				"imacron" : ["i_left", "i_right"],
				"iogonek" : ["i_left", "i_right"],
				"itilde" : ["i_left", "i_right"],
				"j" : ["j_left", "i_right"],
				"dotlessj" : ["j_left", "u_right"],
				"jdotless" : ["j_left", "u_right"],
				"jcircumflex" : ["j_left", "i_right"],
				"k" : ["l_left", "k_right"],
				"kcommaaccent" : ["l_left", "k_right"],
				"kgreenlandic" : ["n_left", "k_right"],
				"l" : ["l_left", "l_right"],
				"lacute" : ["l_left", "l_right"],
				"lcaron" : ["l_left", "lcaron_right"],
				"lcommaaccent" : ["l_left", "l_right"],
				"ldot" : ["l_left", "l_right"],
				"lslash" : ["l_left", "l_right"],
				"m" : ["n_left", "n_right"],
				"n" : ["n_left", "n_right"],
				"nacute" : ["n_left", "n_right"],
				"napostrophe" : ["napostrophe_left", "n_right"],
				"ncaron" : ["n_left", "n_right"],
				"ncommaaccent" : ["n_left", "n_right"],
				"eng" : ["n_left", "n_right"],
				"ntilde" : ["n_left", "n_right"],
				"o" : ["o_left", "o_right"],
				"oacute" : ["o_left", "o_right"],
				"obreve" : ["o_left", "o_right"],
				"ocircumflex" : ["o_left", "o_right"],
				"odieresis" : ["o_left", "o_right"],
				"ograve" : ["o_left", "o_right"],
				"ohungarumlaut" : ["o_left", "o_right"],
				"omacron" : ["o_left", "o_right"],
				"oslash" : ["o_left", "o_right"],
				"oslashacute" : ["o_left", "o_right"],
				"otilde" : ["o_left", "o_right"],
				"oe" : ["o_left", "e_right"],
				"p" : ["n_left", "bowl_right"],
				"thorn" : ["l_left", "bowl_right"],
				"q" : ["bowl_left", "u_right"],
				"r" : ["n_left", "r_right"],
				"racute" : ["n_left", "r_right"],
				"rcaron" : ["n_left", "r_right"],
				"rcommaaccent" : ["n_left", "r_right"],
				"s" : ["s_left", "s_right"],
				"sacute" : ["s_left", "s_right"],
				"scaron" : ["s_left", "s_right"],
				"scedilla" : ["s_left", "s_right"],
				"scircumflex" : ["s_left", "s_right"],
				"scommaaccent" : ["s_left", "s_right"],
				"t" : ["t_left", "t_right"],
				"tbar" : ["t_left", "t_right"],
				"tcaron" : ["t_left", "t_right"],
				"tcedilla" : ["t_left", "t_right"],
				"tcommaaccent" : ["t_left", "t_right"],
				"u" : ["u_left", "u_right"],
				"uacute" : ["u_left", "u_right"],
				"ubreve" : ["u_left", "u_right"],
				"ucircumflex" : ["u_left", "u_right"],
				"udieresis" : ["u_left", "u_right"],
				"ugrave" : ["u_left", "u_right"],
				"uhungarumlaut" : ["u_left", "u_right"],
				"umacron" : ["u_left", "u_right"],
				"uogonek" : ["u_left", "u_right"],
				"uring" : ["u_left", "u_right"],
				"utilde" : ["u_left", "u_right"],
				"v" : ["v_left", "v_right"],
				"w" : ["w_left", "w_right"],
				"wacute" : ["w_left", "w_right"],
				"wcircumflex" : ["w_left", "w_right"],
				"wdieresis" : ["w_left", "w_right"],
				"wgrave" : ["w_left", "w_right"],
				"x" : ["x_left", "x_right"],
				"y" : ["y_left", "y_right"],
				"yacute" : ["y_left", "y_right"],
				"ycircumflex" : ["y_left", "y_right"],
				"ydieresis" : ["y_left", "y_right"],
				"ygrave" : ["y_left", "y_right"],
				"z" : ["z_left", "z_right"],
				"zacute" : ["z_left", "z_right"],
				"zcaron" : ["z_left", "z_right"],
				"zdotaccent" : ["z_left", "z_right"],
				"schwa" : ["schwa_left", "o_right"],
			#liga
				"f_b" : ["f_left", "bowl_right"],
				"f_f" : ["f_left", "f_right"],
				"f_f_b" : ["f_left", "bowl_right"],
				"f_f_h" : ["f_left", "n_right"],
				"f_f_i" : ["f_left", "i_right"],
				"f_f_j" : ["f_left", "i_right"],
				"f_f_k" : ["f_left", "k_right"],
				"f_f_l" : ["f_left", "l_right"],
				"f_f_t" : ["f_left", "t_right"],
				"f_h" : ["f_left", "n_right"],
				"f_i" : ["f_left", "i_right"],
				"f_j" : ["f_left", "i_right"],
				"f_k" : ["f_left", "k_right"],
				"f_l" : ["f_left", "l_right"],
				"f_t" : ["f_left", "t_right"],
				"t_f" : ["t_left", "f_right"],
				"t_t" : ["t_left", "t_right"],
				"fi" : ["f_left", "i_right"],
				"fl" : ["f_left", "l_right"],
				"ordfeminine" : ["ord_a_left", "ord_a_right"],
				"ordmasculine" : ["ord_o_left", "ord_o_right"],
				"mu" : ["n_left", "mu_right"],
			#a.alt
				"a.alt" : ["bowl_left", "u_right"],
				"aacute.alt" : ["bowl_left", "u_right"],
				"abreve.alt" : ["bowl_left", "u_right"],
				"acaron.alt" : ["bowl_left", "u_right"],
				"acircumflex.alt" : ["bowl_left", "u_right"],
				"adieresis.alt" : ["bowl_left", "u_right"],
				"agrave.alt" : ["bowl_left", "u_right"],
				"amacron.alt" : ["bowl_left", "u_right"],
				"aogonek.alt" : ["bowl_left", "u_right"],
				"aring.alt" : ["bowl_left", "u_right"],
				"aringacute.alt" : ["bowl_left", "u_right"],
				"atilde.alt" : ["bowl_left", "u_right"],
				"ae.alt" : ["bowl_left", "e_right"],
				"aeacute.alt" : ["bowl_left", "e_right"],
			#g.alt
				"g.alt" : ["g_bi_left", "g_bi_right"],
				"gbreve.alt" : ["g_bi_left", "g_bi_right"],
				"gcircumflex.alt" : ["g_bi_left", "g_bi_right"],
				"gcommaaccent.alt" : ["g_bi_left", "g_bi_right"],
				"gdotaccent.alt" : ["g_bi_left", "g_bi_right"]
			}

			groupsLCcursive = {
				"a" : ["bowl_left", "bowl_right"],
				"aacute" : ["bowl_left", "bowl_right"],
				"abreve" : ["bowl_left", "bowl_right"],
				"acircumflex" : ["bowl_left", "bowl_right"],
				"adieresis" : ["bowl_left", "bowl_right"],
				"agrave" : ["bowl_left", "bowl_right"],
				"amacron" : ["bowl_left", "bowl_right"],
				"aogonek" : ["bowl_left", "bowl_right"],
				"aring" : ["bowl_left", "bowl_right"],
				"aringacute" : ["bowl_left", "bowl_right"],
				"atilde" : ["bowl_left", "bowl_right"],
				"ae" : ["a_left", "e_right"],
				"aeacute" : ["a_left", "e_right"],
				"b" : ["l_left", "bowl_right"],
				"c" : ["o_left", "c_right"],
				"cacute" : ["o_left", "c_right"],
				"ccaron" : ["o_left", "c_right"],
				"ccedilla" : ["o_left", "c_right"],
				"ccircumflex" : ["o_left", "c_right"],
				"cdotaccent" : ["o_left", "c_right"],
				"d" : ["bowl_left", "l_right"],
				"eth" : ["eth_left", "eth_right"],
				"dcaron" : ["bowl_left", "lcaron_right"],
				"dcroat" : ["bowl_left", "l_right"],
				"e" : ["o_left", "e_right"],
				"eacute" : ["o_left", "e_right"],
				"ebreve" : ["o_left", "e_right"],
				"ecaron" : ["o_left", "e_right"],
				"ecircumflex" : ["o_left", "e_right"],
				"edieresis" : ["o_left", "e_right"],
				"edotaccent" : ["o_left", "e_right"],
				"egrave" : ["o_left", "e_right"],
				"emacron" : ["o_left", "e_right"],
				"eogonek" : ["o_left", "e_right"],
				"f" : ["f_left", "f_right"],
				"g" : ["bowl_left", "u_right"],
				"gbreve" : ["bowl_left", "u_right"],
				"gcircumflex" : ["bowl_left", "u_right"],
				"gcommaaccent" : ["bowl_left", "u_right"],
				"gdotaccent" : ["bowl_left", "u_right"],
				"h" : ["l_left", "n_right"],
				"hbar" : ["l_left", "n_right"],
				"hcircumflex" : ["l_left", "n_right"],
				"i" : ["i_left", "i_right"],
				"dotlessi" : ["n_left", "u_right"],
				"idotless" : ["n_left", "u_right"],
				"iacute" : ["i_left", "i_right"],
				"ibreve" : ["i_left", "i_right"],
				"icircumflex" : ["i_left", "i_right"],
				"idieresis" : ["i_left", "i_right"],
				"idotaccent" : ["i_left", "i_right"],
				"igrave" : ["i_left", "i_right"],
				"ij" : ["i_left", "i_right"],
				"imacron" : ["i_left", "i_right"],
				"iogonek" : ["i_left", "i_right"],
				"itilde" : ["i_left", "i_right"],
				"j" : ["i_left", "i_right"],
				"dotlessj" : ["j_left", "u_right"],
				"jdotless" : ["j_left", "u_right"],
				"jcircumflex" : ["i_left", "i_right"],
				"k" : ["l_left", "k_right"],
				"kcommaaccent" : ["l_left", "k_right"],
				"kgreenlandic" : ["n_left", "k_right"],
				"l" : ["l_left", "l_right"],
				"lacute" : ["l_left", "l_right"],
				"lcaron" : ["l_left", "l_right"],
				"lcommaaccent" : ["l_left", "l_right"],
				"ldot" : ["l_left", "l_right"],
				"lslash" : ["lslash_left", "lslash_right"],
				"m" : ["n_left", "n_right"],
				"n" : ["n_left", "n_right"],
				"nacute" : ["n_left", "n_right"],
				"napostrophe" : ["napostrophe_left", "n_right"],
				"ncaron" : ["n_left", "n_right"],
				"ncommaaccent" : ["n_left", "n_right"],
				"eng" : ["n_left", "n_right"],
				"ntilde" : ["n_left", "n_right"],
				"o" : ["o_left", "o_right"],
				"oacute" : ["o_left", "o_right"],
				"obreve" : ["o_left", "o_right"],
				"ocircumflex" : ["o_left", "o_right"],
				"odieresis" : ["o_left", "o_right"],
				"ograve" : ["o_left", "o_right"],
				"ohungarumlaut" : ["o_left", "o_right"],
				"omacron" : ["o_left", "o_right"],
				"oslash" : ["o_left", "o_right"],
				"oslashacute" : ["o_left", "o_right"],
				"otilde" : ["o_left", "o_right"],
				"oe" : ["o_left", "e_right"],
				"p" : ["n_left", "bowl_right"],
				"thorn" : ["l_left", "bowl_right"],
				"q" : ["bowl_left", "u_right"],
				"r" : ["n_left", "r_right"],
				"racute" : ["n_left", "r_right"],
				"rcaron" : ["n_left", "r_right"],
				"rcommaaccent" : ["n_left", "r_right"],
				"s" : ["s_left", "s_right"],
				"sacute" : ["s_left", "s_right"],
				"scaron" : ["s_left", "s_right"],
				"scedilla" : ["s_left", "s_right"],
				"scircumflex" : ["s_left", "s_right"],
				"scommaaccent" : ["s_left", "s_right"],
				"t" : ["t_left", "t_right"],
				"tbar" : ["t_left", "t_right"],
				"tcaron" : ["t_left", "tcaron_right"],
				"tcedilla" : ["t_left", "t_right"],
				"tcommaaccent" : ["t_left", "t_right"],
				"u" : ["u_left", "u_right"],
				"uacute" : ["u_left", "u_right"],
				"ubreve" : ["u_left", "u_right"],
				"ucircumflex" : ["u_left", "u_right"],
				"udieresis" : ["u_left", "u_right"],
				"ugrave" : ["u_left", "u_right"],
				"uhungarumlaut" : ["u_left", "u_right"],
				"umacron" : ["u_left", "u_right"],
				"uogonek" : ["u_left", "u_right"],
				"uring" : ["u_left", "u_right"],
				"utilde" : ["u_left", "u_right"],
				"v" : ["v_left", "v_right"],
				"w" : ["w_left", "w_right"],
				"wacute" : ["w_left", "w_right"],
				"wcircumflex" : ["w_left", "w_right"],
				"wdieresis" : ["w_left", "w_right"],
				"wgrave" : ["w_left", "w_right"],
				"x" : ["x_left", "x_right"],
				"y" : ["y_left", "y_right"],
				"yacute" : ["y_left", "y_right"],
				"ycircumflex" : ["y_left", "y_right"],
				"ydieresis" : ["y_left", "y_right"],
				"ygrave" : ["y_left", "y_right"],
				"z" : ["z_left", "z_right"],
				"zacute" : ["z_left", "z_right"],
				"zcaron" : ["z_left", "z_right"],
				"zdotaccent" : ["z_left", "z_right"],
				"schwa" : ["schwa_left", "o_right"],
				"f_f" : ["f_left", "f_right"],
				"f_f_i" : ["f_left", "i_right"],
				"f_f_l" : ["f_left", "l_right"],
				"f_i" : ["f_left", "i_right"],
				"f_l" : ["f_left", "l_right"],
				"fi" : ["f_left", "i_right"],
				"fl" : ["f_left", "l_right"]
			}
	
			groupsMS = {
			#punctuation
				"period" : ["period_left", "period_right"],
				"comma" : ["comma_left", "period_right"],
				"colon" : ["colon_left", "colon_right"],
				"semicolon" : ["colon_left", "colon_right"],
				"ellipsis" : ["period_left", "period_right"],
				"horizontalelipsis" : ["period_left", "period_right"],
				"exclam" : ["exclam_left", "exclam_right"],
				"exclamdouble" : ["exclam_left", "exclam_right"],
				"exclamdown" : ["exclam_d_left", "exclam_d_right"],
				"question" : ["question_left", "question_right"],
				"questiondown" : ["question_d_left", "question_d_right"],
				"periodcentered" : ["period_c_left", "period_c__right"],
				"bullet" : ["bullet_left", "bullet_right"],	
				"asterisk" : ["asterisk_left", "asterisk_right"],
				"numbersign" : ["numbersign_left", "numbersign_right"],
				"slash" : ["slash_left", "slash_right"],
				"backslash" : ["b_slash_left", "b_slash_right"],
				"hyphen" : ["dash_left", "dash_right"],
				"hyphentwo" : ["dash_left", "dash_right"],
				"softhyphen" : ["dash_left", "dash_right"],
				"endash" : ["dash_left", "dash_right"],
				"emdash" : ["dash_left", "dash_right"],
				"horizontalbar" : ["dash_left", "dash_right"],
				"underscore" : ["unscore_left", "unscore_right"],
			#brackets
				"parenleft" : ["parenleft_left", "parenleft_right"],
				"parenright" : ["parenright_left", "parenright_right"],
				"braceleft" : ["braceleft_left", "braceleft_right"],
				"braceright" : ["braceright_left", "braceright_right"],
				"bracketleft" : ["bracketleft_left", "bracketleft_right"],
				"bracketright" : ["bracketright_left", "bracketright_right"],
			#quotes
				"quotesinglbase" : ["comma_left", "period_right"],
				"quotedblbase" : ["comma_left", "period_right"],
				"quoteleft" : ["quoteleft_left", "quoteleft_right"],
				"quotedblleft" : ["quoteleft_left", "quoteleft_right"],
				"quoteright" : ["quoteright_left", "quoteright_right"],
				"quotedblright" : ["quoteright_left", "quoteright_right"],
			######
				"guilsinglleft" : ["guilsingl_l_left", "guilsingl_l_right"],
				"guillemetleft" : ["guilsingl_l_left", "guilsingl_l_right"],
				"guilsinglright" : ["guilsingl_r_left", "guilsingl_r_right"],
				"guillemetright" : ["guilsingl_r_left", "guilsingl_r_right"],
			######
				"quotesingle" : ["quote_left", "quote_right"],
				"quotedbl" : ["quote_left", "quote_right"],
			#symbols
				"at" : ["at_left", "at_right"],
				"ampersand" : ["ampersand_left", "ampersand_right"],
				"paragraph" : ["paragraph_left", "H_right"],	
				"section" : ["section_left", "section_right"],
				"copyright" : ["round_u_left", "round_u_right"],
				"registered" : ["round_u_left", "round_u_right"],
				"trademark" : ["TM_left", "TM_right"],
				"degree" : ["degree_left", "degree_right"],
				"bar" : ["bar_left", "bar_right"],	
				"brokenbar" : ["bar_left", "bar_right"],
			#currency
				"Euro" : ["Euro_left", "Euro_right"],
				"cent" : ["cent_left", "cent_right"],
				"dollar" : ["dollar_left", "dollar_right"],
				"currency" : ["currency_left", "currency_right"],
				"sterling" : ["sterling_left", "sterling_right"],
				"yen" : ["yen_left", "yen_right"],
			#math_symbols
				"plus" : ["plus_left", "plus_right"],
				"minus" : ["minus_left", "minus_right"],
				"multiply" : ["greater_left", "less_right"],
				"divide" : ["plus_left", "plus_right"],
				"equal" : ["equal_left", "equal_right"],
				"notequal" : ["equal_left", "equal_right"],
				"greater" : ["greater_left", "greater_right"],
				"less" : ["less_left", "less_right"],
				"greaterequal" : ["greater_left", "greater_right"],
				"lessequal" : ["less_left", "less_right"],
				"plusminus" : ["less_left", "less_right"],
				"approxequal" : ["equal_left", "equal_right"],
				"asciitilde" : ["minus_left", "minus_right"],
				"logicalnot" : ["minus_left", "equal_right"],
				"asciicircum" : ["asciicircum_left", "asciicircum_right"],
				"micro" : ["n_left", "mu_right"],				
				"percent" : ["percent_left", "percent_right"],
				"perthousand" : ["percent_left", "percent_right"],
			#separators
				"space" : ["space_left", "space_right"],
				"nbspace" : ["space_left", "space_right"],
			#numbers	
				"zero" : ["zero_left", "zero_right"],	
				"zeroslash" : ["zero_left", "zero_right"],	
				"one" : ["one_left", "H_right"],	
				"two" : ["two_left", "two_right"],
				"three" : ["three_left", "three_right"],
				"four" : ["four_left", "four_right"],
				"five" : ["five_left", "five_right"],
				"six" : ["six_left", "six_right"],
				"seven" : ["seven_left", "seven_right"],
				"eight" : ["eight_left", "eight_right"],
				"nine" : ["nine_left", "nine_right"],
			#denominators	
				"zero.denominator" : ["zero_de_left", "zero_de_right"],	
				"one.denominator" : ["one_de_left", "one_de_right"],	
				"two.denominator" : ["two_de_left", "two_de_right"],
				"three.denominator" : ["three_de_left", "three_de_right"],
				"four.denominator" : ["four_de_left", "four_de_right"],
				"five.denominator" : ["five_de_left", "five_de_right"],
				"six.denominator" : ["six_de_left", "six_de_right"],
				"seven.denominator" : ["seven_de_left", "seven_de_right"],
				"eight.denominator" : ["eight_de_left", "eight_de_right"],
				"nine.denominator" : ["nine_de_left", "nine_de_right"],
			#numerators	
				"zero.numerator" : ["zero_nu_left", "zero_nu_right"],	
				"one.numerator" : ["one_nu_left", "one_nu_right"],	
				"two.numerator" : ["two_nu_left", "two_nu_right"],
				"three.numerator" : ["three_nu_left", "three_nu_right"],
				"four.numerator" : ["four_nu_left", "four_nu_right"],
				"five.numerator" : ["five_nu_left", "five_nu_right"],
				"six.numerator" : ["six_nu_left", "six_nu_right"],
				"seven.numerator" : ["seven_nu_left", "seven_nu_right"],
				"eight.numerator" : ["eight_nu_left", "eight_nu_right"],
				"nine.numerator" : ["nine_nu_left", "nine_nu_right"],
			#fractions	
				"fraction" : ["fraction_left", "fraction_right"],	
				"onehalf" : ["one_nu_left", "two_de_right"],	
				"onequarter" : ["one_nu_left", "four_de_righ"],
				"threequarters" : ["three_nu_left", "four_de_righ"],
			#sinf	
				"zero.sinf" : ["zero_sinf_left", "zero_sinf_right"],	
				"one.sinf" : ["one_sinf_left", "one_sinf_right"],	
				"two.sinf" : ["two_sinf_left", "two_sinf_right"],
				"three.sinf" : ["three_sinf_left", "three_sinf_right"],
				"four.sinf" : ["four_sinf_left", "four_sinf_right"],
				"five.sinf" : ["five_sinf_left", "five_sinf_right"],
				"six.sinf" : ["six_sinf_left", "six_sinf_right"],
				"seven.sinf" : ["seven_sinf_left", "seven_sinf_right"],
				"eight.sinf" : ["eight_sinf_left", "eight_sinf_right"],
				"nine.sinf" : ["nine_sinf_left", "nine_sinf_right"],
			#subscript	
				"zerosubscript" : ["zero_sinf_left", "zero_sinf_right"],	
				"onesubscript" : ["one_sinf_left", "one_sinf_right"],	
				"twosubscript" : ["two_sinf_left", "two_sinf_right"],
				"threesubscript" : ["three_sinf_left", "three_sinf_right"],
				"foursubscript" : ["four_sinf_left", "four_sinf_right"],
				"fivesubscript" : ["five_sinf_left", "five_sinf_right"],
				"sixsubscript" : ["six_sinf_left", "six_sinf_right"],
				"sevensubscript" : ["seven_sinf_left", "seven_sinf_right"],
				"eightsubscript" : ["eight_sinf_left", "eight_sinf_right"],
				"ninesubscript" : ["nine_sinf_left", "nine_sinf_right"],
			#superior	
				"zerosuperior" : ["zero_sup_left", "zero_sup_right"],	
				"onesuperior" : ["one_sup_left", "one_sup_right"],	
				"twosuperior" : ["two_sup_left", "two_sup_right"],
				"threesuperior" : ["three_sup_left", "three_sup_right"],
				"foursuperior" : ["four_sup_left", "four_sup_right"],
				"fivesuperior" : ["five_sup_left", "five_sup_right"],
				"sixsuperior" : ["six_sup_left", "six_sup_right"],
				"sevensuperior" : ["seven_sup_left", "seven_sup_right"],
				"eightsuperior" : ["eight_sup_left", "eight_sup_right"],
				"ninesuperior" : ["nine_sup_left", "nine_sup_right"],	
			#superscript	
				"zerosuperscript" : ["zero_sup_left", "zero_sup_right"],	
				"onesuperscript" : ["one_sup_left", "one_sup_right"],	
				"twosuperscript" : ["two_sup_left", "two_sup_right"],
				"threesuperscript" : ["three_sup_left", "three_sup_right"],
				"foursuperscript" : ["four_sup_left", "four_sup_right"],
				"fivesuperscript" : ["five_sup_left", "five_sup_right"],
				"sixsuperscript" : ["six_sup_left", "six_sup_right"],
				"sevensuperscript" : ["seven_sup_left", "seven_sup_right"],
				"eightsuperscript" : ["eight_sup_left", "eight_sup_right"],
				"ninesuperscript" : ["nine_sup_left", "nine_sup_right"]		
			}
	
			thisFont.disableUpdateInterface() # suppresses UI updates in Font View
			isNeeded = {}
			for glyph in thisFont.glyphs:
				isNeeded[glyph.name] = False
			if self.w.radioButton.get() == 1:
				for layer in thisFont.selectedLayers:
					isNeeded[layer.parent.name] = True
			else:
				for glyph in thisFont.glyphs:
					isNeeded[glyph.name] = True

			for key in groupsUC:
				if thisFont.glyphs[key] and isNeeded[key]:
					thisFont.glyphs[key].setLeftKerningGroup_(groupsUC[key][0])
					thisFont.glyphs[key].setRightKerningGroup_(groupsUC[key][1])
				if thisFont.glyphs[key.lower()+".sc"] and isNeeded[key]:
					thisFont.glyphs[key.lower()+".sc"].setLeftKerningGroup_(re.sub("_left", "_left_SC",groupsUC[key][0]))
					thisFont.glyphs[key.lower()+".sc"].setRightKerningGroup_(re.sub("_right", "_right_SC",groupsUC[key][1]))
				elif thisFont.glyphs[key.lower()+".smcp"] and isNeeded[key]:
					thisFont.glyphs[key.lower()+".smcp"].setLeftKerningGroup_(re.sub("_left", "_left_SC",groupsUC[key][0]))
					thisFont.glyphs[key.lower()+".smcp"].setRightKerningGroup_(re.sub("_right", "_right_SC",groupsUC[key][1]))

				if sender == self.w.allcapButton:
					if thisFont.glyphs[key] and isNeeded[key]:
						try:
							thisFont.glyphs[key.lower()].setLeftKerningGroup_(groupsUC[key][0])
							thisFont.glyphs[key.lower()].setRightKerningGroup_(groupsUC[key][1])
						except:
							print(key.lower())

			for key in groupsMS:
				if thisFont.glyphs[key] and isNeeded[key]:
					thisFont.glyphs[key].setLeftKerningGroup_(groupsMS[key][0])
					thisFont.glyphs[key].setRightKerningGroup_(groupsMS[key][1])
				if (thisFont.glyphs[key.lower()+".case"] or thisFont.glyphs[key.lower()+".smcp"]) and isNeeded[key]:
					thisFont.glyphs[key].setLeftKerningGroup_(re.sub("MSC_", "MSC_UC_",groupsMS[key][0]))
					thisFont.glyphs[key].setRightKerningGroup_(re.sub("MSC_", "MSC_UC_",groupsMS[key][1]))
			
			if sender == self.w.normalButton:
				for key in groupsLCnormal:
					if thisFont.glyphs[key] and isNeeded[key]:
						thisFont.glyphs[key].setLeftKerningGroup_(groupsLCnormal[key][0])
						thisFont.glyphs[key].setRightKerningGroup_(groupsLCnormal[key][1])
			elif sender == self.w.cursiveButton:
				for key in groupsLCcursive:
					if thisFont.glyphs[key] and isNeeded[key]:
						thisFont.glyphs[key].setLeftKerningGroup_(groupsLCcursive[key][0])
						thisFont.glyphs[key].setRightKerningGroup_(groupsLCcursive[key][1])

			thisFont.enableUpdateInterface() # re-enables UI updates in Font View
					
			
			self.w.close() # delete if you want window to stay open
		except Exception as e:
			# brings macro window to front and reports error:
			Glyphs.showMacroWindow()
			print(" SetKernPairsMain Error: %s" % e)

SetKernPairs()