[input]
comparison_mode = "glyphstream"
text = [
    ":Google_logo :google_logo",
    ":google_super_g_logo :google_super_G_logo :Google_super_g_logo :Google_super_G_logo",
    ":google_G_logo :Google_G_logo",
    ":google_o_logo :Google_o_logo",
    ":google_g_logo :Google_g_logo",
    ":google_l_logo :Google_l_logo",
    ":google_e_logo :Google_e_logo",
    "09:30 1:20pm",
]

[input.features]
calt = true
