[input]
comparison_mode = "glyphstream"
text = [
    "Google_logo google_logo",
    "google_G google_g",
    "super_G_logo super_g_logo",
    "G_logo",
    "e_logo",
    "g_logo",
    "l_logo",
    "o_logo",
    "09:30 1:20pm",
]

[input.features]
calt = true
