[input]
comparison_mode = "glyphstream"
text = [
    "0123456789",
    "09:30 1:20pm",
    "@[](){}¿¡-–—‹›«»·•",
    "#%‰‱",
    "°℉℃",
    "¢$₣£¤¥₤₩₫₮₸₹₺₽₱₴₪ƒ€",
    "Μήλα ή αχλάδια",
    "ΜΗΛΑ Ή ΑΧΛΑΔΙΑ",
]

[input.features]
case = true
