[input]
comparison_mode = "glyphstream"
text = [
    "Á",
    "Ă",
    "Ắ",
    "Ặ",
    "Ằ",
    "Ẳ",
    "Ẵ",
    "Ǎ",
    "Â",
    "Ấ",
    "Ậ",
    "Ầ",
    "Ẩ",
    "Ẫ",
    "Ä",
    "Ạ",
    "À",
    "Ả",
    "Ā",
    "Ą",
    "Å",
    "Ã",
    "Ć",
    "Č",
    "Ç",
    "Ċ",
    "Ď",
    "É",
    "Ě",
    "Ê",
    "Ế",
    "Ệ",
    "Ề",
    "Ể",
    "Ễ",
    "Ë",
    "Ė",
    "Ẹ",
    "È",
    "Ẻ",
    "Ē",
    "Ę",
    "Ẽ",
    "Ğ",
    "Ģ",
    "Ġ",
    "Í",
    "Î",
    "Ï",
    "İ",
    "Ị",
    "Ì",
    "Ỉ",
    "Ī",
    "Į",
    "Ĩ",
    "Ķ",
    "Ĺ",
    "Ľ",
    "Ļ",
    "Ń",
    "Ň",
    "Ņ",
    "Ṅ",
    "Ñ",
    "Ó",
    "Ô",
    "Ố",
    "Ộ",
    "Ồ",
    "Ổ",
    "Ỗ",
    "Ö",
    "Ọ",
    "Ò",
    "Ỏ",
    "Ơ",
    "Ớ",
    "Ợ",
    "Ờ",
    "Ở",
    "Ỡ",
    "Ő",
    "Ō",
    "Õ",
    "Ŕ",
    "Ř",
    "Ŗ",
    "Ś",
    "Š",
    "Ş",
    "Ș",
    "Ṣ",
    "Ť",
    "Ţ",
    "Ț",
    "Ú",
    "Ŭ",
    "Û",
    "Ü",
    "Ụ",
    "Ù",
    "Ủ",
    "Ư",
    "Ứ",
    "Ự",
    "Ừ",
    "Ử",
    "Ữ",
    "Ű",
    "Ū",
    "Ų",
    "Ů",
    "Ũ",
    "Ẃ",
    "Ŵ",
    "Ẅ",
    "Ẁ",
    "Ý",
    "Ŷ",
    "Ÿ",
    "Ỵ",
    "Ỳ",
    "Ỷ",
    "Ỹ",
    "Ź",
    "Ž",
    "Ż",
    "á",
    "ă",
    "ắ",
    "ặ",
    "ằ",
    "ẳ",
    "ẵ",
    "ǎ",
    "â",
    "ấ",
    "ậ",
    "ầ",
    "ẩ",
    "ẫ",
    "ä",
    "ạ",
    "à",
    "ả",
    "ā",
    "ą",
    "å",
    "ã",
    "ć",
    "č",
    "ç",
    "ċ",
    "ď",
    "é",
    "ě",
    "ê",
    "ế",
    "ệ",
    "ề",
    "ể",
    "ễ",
    "ë",
    "ė",
    "ẹ",
    "è",
    "ẻ",
    "ē",
    "ę",
    "ẽ",
    "ğ",
    "ģ",
    "ġ",
    "í",
    "î",
    "ï",
    "ị",
    "ì",
    "ỉ",
    "ī",
    "į",
    "ĩ",
    "ķ",
    "ĺ",
    "ľ",
    "ļ",
    "ń",
    "ň",
    "ņ",
    "ṅ",
    "≠",
    "ñ",
    "ó",
    "ô",
    "ố",
    "ộ",
    "ồ",
    "ổ",
    "ỗ",
    "ö",
    "ọ",
    "ò",
    "ỏ",
    "ơ",
    "ớ",
    "ợ",
    "ờ",
    "ở",
    "ỡ",
    "ő",
    "ō",
    "õ",
    "ŕ",
    "ř",
    "ŗ",
    "ś",
    "š",
    "ş",
    "ș",
    "ṣ",
    "ť",
    "ţ",
    "ț",
    "ú",
    "ŭ",
    "û",
    "ü",
    "ụ",
    "ù",
    "ủ",
    "ư",
    "ứ",
    "ự",
    "ừ",
    "ử",
    "ữ",
    "ű",
    "ū",
    "ų",
    "ů",
    "ũ",
    "ẃ",
    "ŵ",
    "ẅ",
    "ẁ",
    "ý",
    "ŷ",
    "ÿ",
    "ỵ",
    "ỳ",
    "ỷ",
    "ỹ",
    "ź",
    "ž",
    "ż",
]

[input.features]
ccmp = true
