[input]
text = [
    "Å",
    "å",
    "Ǻ",
    "ǻ",
    "ìíîĩīĭi̇ïi̊i̋ǐi̒ỉ",
    "j̀j́ĵj̃j̄j̆j̇j̈j̊j̋ǰj̒j̉",
    "į̀į́į̂į̃į̄į̆į̇į̈į̊į̋į̌į̒į̉",
    "ị̀ị́ị̂ị̃ị̄ị̆ị̇ị̈ị̊ị̋ị̌ị̒ị̉",
]

[input.features]
ccmp = true
