[input]
comparison_mode = "glyphstream"
text = [
    "fb",
    "ff",
    "ffb",
    "ffh",
    "ffi",
    "ffj",
    "ffk",
    "ffl",
    "fft",
    "fh",
    "fi",
    "fj",
    "fk",
    "fl",
    "ft",
    "tf",
    "tt",
    "Google_logo google_logo Googlelogoligature googlelogoligature",
    "Glogoligature",
    "ologoligature",
    "glogoligature",
    "llogoligature",
    "elogoligature",
]

[input.features]
liga = true
