[input]
comparison_mode = "glyphstream"
language = "lt"
text = [
    # https://github.com/googlefonts/googlesans-flex/blob/e68ca67618d3757911c6c3f45f8ab0e2df7f629b/sources/GoogleSansFlex-wg400-wd100-oz18-GD0-RD0-sl0.ufo/features.fea#L31
    "ı̀ ı́ ı̂ ı̃ ı̄ ı̆ ı̇ ı̈ ı̊ ı̋ ı̌ ı̒",
]

[input.features]
