[input]
comparison_mode = "glyphstream"
text = [
    "0a 1a 2a 3a 4a 5a 6a 7a 8a 9a",
    "0.a 1.a 2.a 3.a 4.a 5.a 6.a 7.a 8.a 9.a",
    "0o 1o 2o 3o 4o 5o 6o 7o 8o 9o",
    "0.o 1.o 2.o 3.o 4.o 5.o 6.o 7.o 8.o 9.o",
]

[input.features]
ordn = true
