[input]
comparison_mode = "glyphstream"
text = [
    "0123456789",
    "12/34",
    "12.34",
    "09:30 1:20pm",
    "01/23/34 01-23-34 01.23.34",
    " .:;,",
    "¢$₣£¤¥₤₩₫₮₸₹₺₽₱₴₪ƒ€₾",
    "§¬#%",
    "+−×÷±<=>≈≠≤≥",
]

[input.features]
tnum = true
