name: Build UFOs
description: Builds fonts using Python tooling

inputs:
  repo-path:
    description: Path to the repository containing the sources & build files
    required: true
    default: '.'

outputs:
  artifact-name:
    description: The name of the zip file containing the fonts
    value: ${{ steps.zip-name.outputs.artifact-name }}

runs:
  using: composite
  steps:
  - name: Set up uv and enable caching
    uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
    with:
      enable-cache: true
      cache-dependency-glob: |
        requirements*.txt
        requirements*.in
  - name: Bump sources version to release tag version
    if: github.event_name == 'release'
    shell: bash
    run: make --directory ${{ inputs.repo-path }} bump-to-tag
  - name: Build the font
    shell: bash
    run: |
      if [[ -d "${{ inputs.repo-path }}/sources-v2_0" ]]; then
        echo "::warning title=Glyphs sources found::Building UFO sources, not the Glyphs sources, I hope this is what you want"
      fi
      make --directory ${{ inputs.repo-path }} build
  - name: Generate archive name
    id: zip-name
    uses: alpha-tango-kilo/gha-artifact-name@49459760611c4a5cedffa13dfb36ca29ab1fdcfc  # v1.3.0
    with:
      repo-name: Google Sans Flex
      repo-root: ${{ inputs.repo-path }}
      overrides: |
        build-glyphs: glyphs
  - name: Upload archive
    uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
    with:
      name: ${{ steps.zip-name.outputs.artifact-name }}
      path: ${{ inputs.repo-path }}/fonts/variable
      if-no-files-found: error
