name: Build UFOs
description: Builds fonts using Python tooling

inputs:
  repo-path:
    description: Path to the repository containing the sources & build files
    required: true
    default: '.'

outputs:
  artifact-name:
    description: The name of the zip file containing the fonts
    value: ${{ steps.zip-name.outputs.artifact-name }}

runs:
  using: composite
  steps:
  - name: Set up venv
    shell: bash
    run: |
      echo "::group::Set up venv"
      make --directory ${{ inputs.repo-path }} venv
      echo "::endgroup::"
  - name: Bump sources version to release tag version
    if: github.event_name == 'release'
    shell: bash
    run: make --directory ${{ inputs.repo-path }} bump-to-tag
  - name: Build the font
    shell: bash
    run: |
      if [[ -d "${{ inputs.repo-path }}/sources-v2_0" ]]; then
        echo "::warning title=Glyphs sources found::Building UFO sources, not the Glyphs sources, I hope this is what you want"
      fi
      make --directory ${{ inputs.repo-path }} build
  - name: Generate archive name
    id: zip-name
    uses: alpha-tango-kilo/gha-artifact-name@v1
    with:
      repo-name: Google Sans Flex
      repo-root: ${{ inputs.repo-path }}
      overrides: |
        build-glyphs: glyphs
  - name: Upload archive
    uses: actions/upload-artifact@v4
    with:
      name: ${{ steps.zip-name.outputs.artifact-name }}
      path: ${{ inputs.repo-path }}/fonts/variable
      if-no-files-found: error
