name: Build font and specimen

on:
  workflow_dispatch:
    inputs:
      branch:
        description: The Git reference to import from (branch name or 7 character commit reference)
        required: true
  release:
    types: [published] # A release, pre-release, or draft of a release was published.

jobs:
  build:
    runs-on: [linux, googlefonts-64cores-256GB]
    timeout-minutes: 60
    steps:
      - name: Get sources
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/cache@v3
        with:
          path: ./venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Generate zip file name
        id: zip-name
        shell: bash
        # Set the archive name to repo name + "-assets" e.g "MavenPro-assets"
        run: echo "ZIP_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')-fonts" >> $GITHUB_ENV
      # If a new release is cut, use the release tag to auto-bump the source files
      - name: Bump release
        if: github.event_name == 'release'
        run: make bump-to-tag
      - name: Build font
        run: make build
      - name: Check with fontbakery
        run: make test
        continue-on-error: true
      - name: Check with OT Sanitizer
        uses: f-actions/opentype-sanitizer@v2
        with:
          path: "fonts/variable/*.ttf"
      - name: proof
        run: make proof
      - name: Analyze file size
        uses: ./.github/actions/file-size
        continue-on-error: true
      - name: Archive fonts & QA reports
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ZIP_NAME }}
          path: |
            fonts
            out
      - name: Archive fonts
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ZIP_NAME }}
          path: fonts
    outputs:
      zip_name: ${{ env.ZIP_NAME }}
  release:
    # only run if the commit is tagged...
    if: github.event_name == 'release'
    # ... and it builds successfully
    needs:
      - build
    runs-on: ubuntu-latest
    env:
      ZIP_NAME: ${{ needs.build.outputs.zip_name }}
    steps:
      - name: Generate zip file name
        shell: bash
        # Set the archive name to "GoogleSansFlex-<git-ref>.zip", where git-ref
        # can be the branch or tag name.
        run: echo "RELEASE_ZIP_NAME=GoogleSansFlex-${GITHUB_REF#refs/*/}.zip" >> "$GITHUB_ENV"
      - uses: actions/checkout@v3
      - name: Download artefact files
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ZIP_NAME }}
          path: ${{ env.ZIP_NAME }}
      - name: Zip files
        run: zip -r ${{ env.RELEASE_ZIP_NAME }} ${{ env.ZIP_NAME }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.RELEASE_ZIP_NAME }}
          asset_name: ${{ env.RELEASE_ZIP_NAME }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "Production ready fonts"
