name: Build from Glyphs package

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: The branch to build from
        required: true

jobs:
  convert:
    runs-on: [linux, googlefonts-64cores-256GB]
    timeout-minutes: 20
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        ref: main
        path: main
    - name: Log & validate inputs
      run: |
        echo "git-ref: ${{ github.event.inputs.git-ref }}"
        echo "python-version-file: $(head -n 1 -z ./main/.github/workflows/python-version.txt)"
        if [[ "${{ github.ref_name }}" != "main" ]]; then
          echo "::error title=Pipeline not run on main::Build from Glyphs workflow should always be run from main"
          exit 1
        fi
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ./main/.github/workflows/python-version.txt
        cache: pip
    - name: Convert Glyphs package sources to UFO
      id: glyphspackage2ufo
      uses: ./main/.github/actions/glyphspackage2ufo
      with:
        git-ref: ${{ github.event.inputs.git-ref }}
    - name: Create sources tarball
      shell: bash
      run: |
        cd "${{ steps.glyphspackage2ufo.outputs.directory }}"
        rm -r venv
        shopt -s dotglob
        tar --create --exclude-vcs --file "UFO sources.tar" *
    - name: Generate sources artifact name
      id: zip-name
      uses: alpha-tango-kilo/gha-artifact-name@v1
      with:
        repo-name: Generated UFO sources
        repo-root: ${{ steps.glyphspackage2ufo.outputs.directory }}
        overrides: |
          build-glyphs: glyphs
    - name: Upload sources tarball
      id: upload-sources
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.zip-name.outputs.artifact-name }}.tar
        path: ${{ steps.glyphspackage2ufo.outputs.directory }}/UFO sources.tar
        compression-level: 9
        if-no-files-found: error
    outputs:
      sources-artifact: ${{ steps.zip-name.outputs.artifact-name }}
  build:
    runs-on: [linux, googlefonts-64cores-256GB]
    timeout-minutes: 15
    needs:
    - convert
    steps:
    - name: Download sources tarball
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.convert.outputs.sources-artifact }}.tar
    - name: Extract sources from tarball
      shell: bash
      run: tar --extract --file "UFO sources.tar"
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ./.github/workflows/python-version.txt
        cache: pip
    - name: Build fonts
      id: build-ufos
      uses: ./.github/actions/build-ufos-py
      env:
        SKIP_FONTV: true
    outputs:
      variable-artifact: ${{ steps.build-ufos.outputs.artifact-name }}
  test:
    needs:
    - convert
    - build
    uses: googlefonts/googlesans-flex/.github/workflows/tests.yml@main
    with:
      artifact-as-branch: ${{ needs.convert.outputs.sources-artifact }}.tar
      artifact-name: ${{ needs.build.outputs.variable-artifact }}
