name: Build from UFOs

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: The Git reference to build from (branch name or 7 character commit reference)
        required: true
  release:
    # A release, pre-release, or draft of a release was published
    types: [published]

jobs:
  build:
    runs-on: [linux, googlefonts-64cores-256GB]
    timeout-minutes: 60
    steps:
    - name: Checkout ${{ inputs.git-ref || 'main' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.git-ref || 'main' }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: ./.github/workflows/python-version.txt
        cache: pip
    - name: Build font
      id: build-ufos
      uses: ./.github/actions/build-ufos-py
    outputs:
      artifact-name: ${{ steps.build-ufos.outputs.artifact-name }}
  test:
    runs-on: [linux, googlefonts-64cores-256GB]
    timeout-minutes: 60
    needs:
    - build
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
    - name: Download built fonts
      uses: actions/download-artifact@v3
      with:
        name: ${{ needs.build-variable.outputs.artifact-name }}
        path: fonts/variable
    - name: Run tests
      uses: ./.github/actions/tests
  release:
    # Only run if the commit is tagged...
    if: github.event_name == 'release'
    # ... and it builds successfully
    needs:
    - build
    - test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Download artifact files
      uses: actions/download-artifact@v3
      with:
        name: ${{ needs.build.outputs.artifact-name }}
        path: ${{ needs.build.outputs.artifact-name }}
    - name: Create release archive
      run: |
        release_zip_name="GoogleSansFlex-${GITHUB_REF#refs/*/}.zip"
        echo "RELEASE_ZIP_NAME=$release_zip_name" >> "$GITHUB_ENV"
        zip -r $release_zip_name "${{ needs.build.outputs.artifact-name }}"
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.RELEASE_ZIP_NAME }}
        asset_name: ${{ env.RELEASE_ZIP_NAME }}
        tag: ${{ github.ref }}
        overwrite: true
        body: "Production ready fonts"
