name: Build from UFOs

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: The branch to build from
        required: true
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - main

jobs:
  build:
    runs-on: [linux, googlefonts-64cores-256GB]
    timeout-minutes: 15
    steps:
    # on: pull_request uses head_ref for branch name, on: push uses ref_name
    - name: Checkout ${{ inputs.git-ref || github.head_ref || github.ref_name }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.git-ref || github.head_ref || github.ref_name }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ./.github/workflows/python-version.txt
        cache: pip
    - name: Build font
      id: build-ufos
      uses: ./.github/actions/build-ufos-py
    outputs:
      artifact-name: ${{ steps.build-ufos.outputs.artifact-name }}
  test:
    needs:
    - build
    uses: googlefonts/googlesans-flex/.github/workflows/tests.yml@main
    with:
      branch: ${{ inputs.git-ref || github.head_ref || github.ref_name }}
      artifact-name: ${{ needs.build.outputs.artifact-name }}
