name: Build from Glyphs package

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: The branch to build from
        required: true

jobs:
  convert:
    runs-on: [linux, googlefonts-64cores-256GB]
    timeout-minutes: 50
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        ref: main
        path: main
    - name: Log & validate inputs
      run: |
        echo "git-ref: ${{ github.event.inputs.git-ref }}"
        echo "python-version-file: $(head -n 1 -z ./main/.github/workflows/python-version.txt)"
        if [[ "${{ github.ref_name }}" != "main" ]]; then
          echo "::error title=Pipeline not run on main::Build from Glyphs workflow should always be run from main"
          exit 1
        fi
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ./main/.github/workflows/python-version.txt
        cache: pip
    - name: Convert Glyphs package sources to UFO
      id: glyphspackage2ufo
      uses: ./main/.github/actions/glyphspackage2ufo
      with:
        git-ref: ${{ github.event.inputs.git-ref }}
    - name: Upload sources
      id: upload-sources
      uses: actions/upload-artifact@v4
      with:
        name: Generated UFO sources
        path: ${{ steps.glyphspackage2ufo.outputs.directory }}/sources
  build-test:
    runs-on: [linux, googlefonts-64cores-256GB]
    timeout-minutes: 50
    needs:
    - convert
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        ref: main
        sparse-checkout: "!sources/"
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ./main/.github/workflows/python-version.txt
    - name: Download sources
      uses: actions/download-artifact@v4
      with:
        name: Generated UFO sources
        path: sources
    - name: Build fonts
      id: build-ufos
      uses: ./main/.github/actions/build-ufos-py
      env:
        SKIP_FONTV: true
    - name: Run tests
      uses: ./main/.github/actions/tests
