name: Progress chart

on:
  workflow_dispatch:

jobs:
  burndown:
    runs-on: [linux, googlefonts-64cores-256GB]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all so we get access to all tags, etc.
      - name: Generate burndown chart
        uses: googlefonts/action-burndown@v0.1
