name: Progress chart

on:
  workflow_dispatch:

jobs:
  burndown:
    runs-on: [linux, googlefonts-64cores-256GB]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all so we get access to all tags, etc.
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: pip
      - name: Cache load
        uses: actions/cache/restore@v3
        with:
          path: scripts/.progress-burndown-cache
          key: progress-chart-${{ hashFiles('scripts/gs-progress-burndown.py') }}
          restore-keys: progress-chart-${{ hashFiles('scripts/gs-progress-burndown.py') }}-
      - name: Generate chart
        env:
          PROGRESS_BURNDOWN_CACHING: 1
        run: make progress-chart
      - name: Upload chart
        uses: actions/upload-artifact@v3
        with:
          name: gs-flex-progress
          path: gs-flex-progress.png
      - name: Cache save
        uses: actions/cache/save@v3
        with:
          path: scripts/.progress-burndown-cache
          key: progress-chart-${{ hashFiles('scripts/gs-progress-burndown.py') }}-${{ hashFiles('scripts/.progress-burndown-cache/**') }}
