# name: Progress chart
# on:
#   push:
#     branches:
#       - fb-wip
#       - import-fb-wip

# jobs:
#   burndown:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0 # Fetch all so we get access to all tags, etc.
#       - name: Set up Python 3.x
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.x"
#       - name: Generate chart
#         run: make progress-chart
#       - name: Upload chart
#         uses: actions/upload-artifact@v3
#         with:
#           path: gs-flex-progress.png
