name: Diffenate builds

on:
  workflow_dispatch:
    inputs:
      before:
        description: The 'before' git reference (tag, branch, or commit)
        required: true
      after:
        description: The 'after' git reference (tag, branch, or commit)
        required: true
      all-masters:
        description: Check all masters? (--masters)
        type: boolean

permissions:
  contents: read

jobs:
  build-before:
    runs-on: googlefonts-64cores-256GB
    timeout-minutes: 15
    steps:
    - name: Checkout ${{ inputs.before }}
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        ref: ${{ inputs.before }}
        persist-credentials: false
    - name: Setup Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
      with:
        python-version-file: .github/workflows/python-version.txt
        cache: pip
    - name: Set up uv and enable caching
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
      with:
        # https://docs.zizmor.sh/audits/#cache-poisoning
        enable-cache: ${{ !startsWith(github.ref, 'refs/tags/') }}
        cache-dependency-glob: |
          requirements*.txt
          requirements*.in
    - name: Build fonts
      run: make build
    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: Before VFs (${{ inputs.before }})
        path: fonts/variable
        if-no-files-found: error
  build-after:
    runs-on: googlefonts-64cores-256GB
    timeout-minutes: 15
    steps:
    - name: Checkout ${{ inputs.after }}
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        ref: ${{ inputs.after }}
        persist-credentials: false
    - name: Setup Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
      with:
        python-version-file: .github/workflows/python-version.txt
    - name: Set up uv and enable caching
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
      with:
        # https://docs.zizmor.sh/audits/#cache-poisoning
        enable-cache: ${{ !startsWith(github.ref, 'refs/tags/') }}
        cache-dependency-glob: |
          requirements*.txt
          requirements*.in
    - name: Build fonts
      run: make build
    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: After VFs (${{ inputs.after }})
        path: fonts/variable
        if-no-files-found: error
  diffenate:
    runs-on: googlefonts-64cores-256GB
    timeout-minutes: 30
    needs:
    - build-before
    - build-after
    steps:
    - name: Download before fonts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
      with:
        name: Before VFs (${{ inputs.before }})
        path: before
    - name: Download after fonts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
      with:
        name: After VFs (${{ inputs.after }})
        path: after
    - name: Install diffenator3
      uses: notofonts/install-diffenator3-action@f11137e5df21a0396dda8e276fbaffbe1df87617
    - name: Run diffenator3
      run: |
        mkdir -p diffenator_report
        if [[ "${INPUT_ALL_MASTERS}" == "true" ]] ; then
          echo "Checking masters"
          LOCATIONS_ARG="--masters"
        else
          echo "Checking instances"
          LOCATIONS_ARG=""
        fi
        diffenator3 before/*.ttf after/*.ttf \
          $LOCATIONS_ARG --html --output diffenator_report
      env:
        INPUT_ALL_MASTERS: ${{ inputs.all-masters }}
    - name: Upload diffenator report
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: Diffenator3 report (${{ inputs.before }} vs ${{ inputs.after }})
        path: diffenator_report
        if-no-files-found: error
        compression-level: 9
