name: Diffenate builds

on:
  workflow_dispatch:
    inputs:
      before:
        description: The 'before' git reference (tag, branch, or commit)
        required: true
      after:
        description: The 'after' git reference (tag, branch, or commit)
        required: true

jobs:
  build-before:
    runs-on: [linux, googlefonts-64cores-256GB]
    timeout-minutes: 15
    steps:
    - name: Checkout ${{ inputs.before }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.before }}
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version-file: .github/workflows/python-version.txt
        cache: pip
    - name: Setup venv
      run: make venv
    - name: Build fonts
      run: make build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Before VFs (${{ inputs.before }})
        path: fonts/variable
        if-no-files-found: error
  build-after:
    runs-on: [linux, googlefonts-64cores-256GB]
    timeout-minutes: 15
    steps:
    - name: Checkout ${{ inputs.after }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.after }}
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version-file: .github/workflows/python-version.txt
        cache: pip
    - name: Setup venv
      run: make venv
    - name: Build fonts
      run: make build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: After VFs (${{ inputs.after }})
        path: fonts/variable
        if-no-files-found: error
  diffenate:
    runs-on: [linux, googlefonts-64cores-256GB]
    timeout-minutes: 90
    needs:
    - build-before
    - build-after
    steps:
    - name: Checkout python-version.txt from main
      uses: actions/checkout@v4
      with:
        sparse-checkout: .github/workflows/python-version.txt
    - name: Download before fonts
      uses: actions/download-artifact@v4
      with:
        name: Before VFs (${{ inputs.before }})
        path: before
    - name: Download after fonts
      uses: actions/download-artifact@v4
      with:
        name: After VFs (${{ inputs.after }})
        path: after
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version-file: .github/workflows/python-version.txt
        cache: pip
    - name: Install diffenator2
      run: pip install --upgrade diffenator2

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
    - name: Setup Chrome Driver
      uses: nanasess/setup-chromedriver@master
    - name: Setup Firefox
      uses: browser-actions/setup-firefox@latest
    - name: Setup Firefox Driver
      uses: browser-actions/setup-geckodriver@latest
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run diffenator2
      run: |
        mkdir -p diffenator_report
        chromedriver --url-base=/wd/hub &
        diffenator2 diff --fonts-before before/*.ttf --fonts-after after/*.ttf \
          --out diffenator_report --imgs
    - name: Upload diffenator report
      uses: actions/upload-artifact@v4
      with:
        name: Diffenator2 report (${{ inputs.before }} vs ${{ inputs.after }})
        path: diffenator_report
        if-no-files-found: error
