name: Diffenate builds

on:
  workflow_dispatch:
    inputs:
      before:
        description: The 'before' git reference (tag, branch, or commit)
        required: true
      after:
        description: The 'after' git reference (tag, branch, or commit)
        required: true
      all-masters:
        description: Check all masters? (--masters)
        type: boolean

jobs:
  build-before:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Checkout ${{ inputs.before }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.before }}
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version-file: .github/workflows/python-version.txt
        cache: pip
    - name: Setup venv
      run: make venv
    - name: Build fonts
      run: make build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Before VFs (${{ inputs.before }})
        path: fonts/variable
        if-no-files-found: error
  build-after:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Checkout ${{ inputs.after }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.after }}
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version-file: .github/workflows/python-version.txt
        cache: pip
    - name: Setup venv
      run: make venv
    - name: Build fonts
      run: make build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: After VFs (${{ inputs.after }})
        path: fonts/variable
        if-no-files-found: error
  diffenate:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs:
    - build-before
    - build-after
    steps:
    - name: Download before fonts
      uses: actions/download-artifact@v4
      with:
        name: Before VFs (${{ inputs.before }})
        path: before
    - name: Download after fonts
      uses: actions/download-artifact@v4
      with:
        name: After VFs (${{ inputs.after }})
        path: after
    - name: Install diffenator3
      uses: notofonts/install-diffenator3-action@f11137e5df21a0396dda8e276fbaffbe1df87617
    - name: Run diffenator3
      run: |
        mkdir -p diffenator_report
        if [[ ${{ inputs.all-masters }} == "true" ]] ; then
          echo "Checking masters"
          LOCATIONS_ARG="--masters"
        else
          echo "Checking instances"
          LOCATIONS_ARG=""
        fi
        diffenator3 before/*.ttf after/*.ttf \
          $LOCATIONS_ARG --html --output diffenator_report
    - name: Upload diffenator report
      uses: actions/upload-artifact@v4
      with:
        name: Diffenator3 report (${{ inputs.before }} vs ${{ inputs.after }})
        path: diffenator_report
        if-no-files-found: error
        compression-level: 9
