name: Update from sources

on:
  workflow_dispatch:
    inputs:
      branch:
        description: The name of the branch to import from
        required: true
      email:
        description: Your GitHub email address (CLA approved)
        required: true

jobs:
  import-branch:
    runs-on: [linux, googlefonts-64cores-256GB]
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - name: Prepare environment
        env:
          SOURCE_BRANCH: ${{ github.event.inputs.branch }}
          TARGET_BRANCH: ${{ format('import-{0}', github.event.inputs.branch) }}
        run: |
          cd "$GITHUB_WORKSPACE/main"

          # The clone is shallow, need to fetch other branches
          git fetch origin "$SOURCE_BRANCH"
          git branch "$SOURCE_BRANCH" "origin/$SOURCE_BRANCH"
          git worktree add --quiet ../source "$SOURCE_BRANCH"

          # Try to fetch, OK if it doesn't exist (we'll create it)
          if git fetch origin "$TARGET_BRANCH" &>/dev/null ; then
            echo "The target branch '$TARGET_BRANCH' already exists, updating."
            git worktree add --quiet ../target "$TARGET_BRANCH"
          else
            echo "The target branch '$TARGET_BRANCH' doesn't exist, creating."
            git fetch origin main # because shallow
            git worktree add --quiet ../target -b "$TARGET_BRANCH" origin/main
          fi
      - name: Run import scripts
        uses: ./main/.github/actions/import
      - name: Commit & push changes
        env:
          SOURCE_BRANCH: ${{ github.event.inputs.branch }}
          TARGET_BRANCH: ${{ format('import-{0}', github.event.inputs.branch) }}
          GIT_EMAIL: ${{ github.event.inputs.email }}
        run: |
          # Create the import commit in the "target" worktree
          cd "$GITHUB_WORKSPACE/target"
          git config user.name "Import Script"
          git config user.email "$GIT_EMAIL"
          git add sources
          git commit --quiet -m "Import from $SOURCE_BRANCH
            
          This commit was creating automatically using the GitHub workflow"
          git push -u origin "$TARGET_BRANCH"
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install yq
        run: |
          sudo apt-get update
          sudo snap install yq
      - uses: actions/cache@v3
        with:
          path: ./venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Generate zip file name
        id: zip-name
        shell: bash
        # Set the archive name to repo name + "-assets" e.g "MavenPro-assets"
        run: echo "ZIP_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')-fonts" >> $GITHUB_ENV
      - name: Build font
        run: cd "$GITHUB_WORKSPACE/target" && make build
      - name: Check with fontbakery
        run: cd "$GITHUB_WORKSPACE/target" && make test
        continue-on-error: true
      - name: proof
        run: cd "$GITHUB_WORKSPACE/target" && make proof
      - name: Analyze file size
        uses: ./main/.github/actions/file-size
        with:
          path: /github/workspace/target
        continue-on-error: true
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ZIP_NAME }}
          path: |
            target/fonts
            target/out
    outputs:
      zip_name: ${{ env.ZIP_NAME }}
