name: Update from sources

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: The branch to import from
        required: true
      email:
        description: Your GitHub email address (CLA approved)
        required: true

jobs:
  import-branch:
    runs-on: [linux, googlefonts-64cores-256GB]
    timeout-minutes: 15
    steps:
      - name: Log & validate inputs
        run: |
          echo "git-ref: ${{ github.event.inputs.git-ref }}"
          echo "git-email: ${{ github.event.inputs.email }}"
          echo "python-version-file: $(head -n 1 -z .github/workflows/python-version.txt)"
          if [[ "${{ github.ref_name }}" != "main" ]]; then
            echo "::error title=Pipeline not run on main::Import workflow should always be run from main"
            exit 1
          fi
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: ./main/.github/workflows/python-version.txt
          cache: pip
      - name: Convert Glyphs package sources to UFO
        id: glyphspackage2ufo
        uses: ./main/.github/actions/glyphspackage2ufo
        with:
          git-ref: ${{ github.event.inputs.git-ref }}
      - name: Create/Update import branch
        id: create-update-import
        uses: ./main/.github/actions/create-import-branch
        with:
          updated-sources: ${{ steps.glyphspackage2ufo.outputs.directory }}
          imported-branch: ${{ github.event.inputs.git-ref }}
          git-email: ${{ github.event.inputs.email }}
    outputs:
      import-branch: ${{ steps.create-update-import.outputs.import-branch }}
  build-variable:
    runs-on: [linux, googlefonts-64cores-256GB]
    timeout-minutes: 15
    needs: import-branch
    steps:
      - name: Checkout ${{ needs.import-branch.outputs.import-branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.import-branch.outputs.import-branch }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: ./.github/workflows/python-version.txt
          cache: pip
      - name: Build fonts
        id: build-ufos
        uses: ./.github/actions/build-ufos-py
    outputs:
      variable-artifact: ${{ steps.build-ufos.outputs.artifact-name }}
  test:
    runs-on: [linux, googlefonts-64cores-256GB]
    timeout-minutes: 20
    needs:
      - import-branch
      - build-variable
    steps:
      - name: Checkout ${{ needs.import-branch.outputs.import-branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.import-branch.outputs.import-branch }}
      - name: Download built fonts
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build-variable.outputs.variable-artifact }}
          path: fonts/variable
      - name: Run tests
        uses: ./.github/actions/tests
