name: Update from sources

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: The Git reference to import from (branch name or 7 character commit reference)
        required: true
      email:
        description: Your GitHub email address (CLA approved)
        required: true

jobs:
  import-branch:
    runs-on: [linux, googlefonts-64cores-256GB]
    steps:
      - name: Log & validate inputs
        run: |
          echo "git-ref: ${{ github.event.inputs.git-ref }}"
          echo "git-email: ${{ github.event.inputs.email }}"
          if [[ "${{ github.ref_name }}" != "main" ]]; then
            echo "::error title=Pipeline not run on main::Import workflow should always be run from main"
          fi
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
      - name: Convert Glyphs package sources to UFO
        id: glyphspackage2ufo
        uses: ./main/.github/actions/glyphspackage2ufo
      - name: Create/Update import branch
        uses: ./main/.github/actions/create-import-branch
        with:
          updated-sources: ${{ steps.glyphspackage2ufo.outputs.directory }}
          imported-branch: ${{ github.event.inputs.git-ref }}
          git-email: ${{ github.event.inputs.email }}

# TODO: re-add build
