name: Release variable & workspace fonts

on:
  release:
    # A release, pre-release, or draft of a release was published
    types: [published]

jobs:
  build-variable:
    runs-on: googlefonts-8cores-32GB
    timeout-minutes: 15
    steps:
    - name: Checkout ${{ github.ref_name }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ./.github/workflows/python-version.txt
        cache: pip
    - name: Build font
      id: build-ufos
      uses: ./.github/actions/build-ufos-py
    outputs:
      artifact-name: ${{ steps.build-ufos.outputs.artifact-name }}
  cut-instances:
    needs:
    - build-variable
    runs-on: googlefonts-16cores-64GB
    timeout-minutes: 10
    steps:
    - name: Checkout ${{ github.ref_name }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ./.github/workflows/python-version.txt
        cache: pip
    - name: Cut workspace fonts
      id: cut-workspace-fonts
      uses: ./.github/actions/cut-workspace-fonts
      with:
        vf-artifact: ${{ needs.build-variable.outputs.artifact-name }}
    - name: Create Android flavour GS Flex
      run: make android
    - name: Generate Android archive name
      id: android-artifact-name
      uses: alpha-tango-kilo/gha-artifact-name@v1
      with:
        repo-name: Google Sans Flex Android
    - name: Upload workspace fonts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.android-artifact-name.outputs.artifact-name }}
        path: fonts/android
        compression-level: 9
        if-no-files-found: error
    outputs:
      android-artifact-name: ${{ steps.android-artifact-name.outputs.artifact-name }}
      workspace-artifact-name: ${{ steps.cut-workspace-fonts.outputs.artifact-name }}
  test-variable:
    needs:
    - build-variable
    uses: googlefonts/googlesans-flex/.github/workflows/tests.yml@main
    with:
      branch: ${{ github.ref_name }}
      artifact-name: ${{ needs.build-variable.outputs.artifact-name }}
  test-workspace-android:
    needs:
    - cut-instances
    runs-on: googlefonts-8cores-32GB
    timeout-minutes: 30
    steps:
    - name: Checkout ${{ github.ref_name }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ./.github/workflows/python-version.txt
        cache: pip
    - name: Download workspace and tv fonts
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.cut-instances.outputs.workspace-artifact-name }}
        path: fonts/
    - name: Check workspace fonts with OT Sanitizer
      uses: f-actions/opentype-sanitizer@v3
      with:
        path: fonts/workspace/*.ttf
    - name: Check tv fonts with OT Sanitizer
      uses: f-actions/opentype-sanitizer@v3
      with:
        path: fonts/tv/*.ttf
    - name: Download Android font
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.cut-instances.outputs.android-artifact-name }}
        path: fonts/android
    - name: Check Android font with OT Sanitizer
      uses: f-actions/opentype-sanitizer@v3
      with:
        path: fonts/android/*.ttf
    - name: Run Fontbakery
      id: fontbakery-workspace
      env:
        SKIP_SOURCES: 1
      run: scripts/fontbakery.sh
    - name: Upload Fontbakery reports
      uses: actions/upload-artifact@v4
      # Always upload reports (even during a pipeline fail), so long as Fontbakery completed
      # https://docs.github.com/en/actions/learn-github-actions/expressions#always
      # https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context
      if: ${{ !cancelled() && (steps.fontbakery-workspace.conclusion == 'success' || steps.fontbakery-workspace.conclusion == 'failure') }}
      with:
        name: Fontbakery workspace & Android reports
        path: out/fontbakery
        if-no-files-found: error
  upload-to-release:
    needs:
    - build-variable
    - cut-instances
    - test-variable
    - test-workspace-android
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
    - name: Download variable fonts
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build-variable.outputs.artifact-name }}
        path: ${{ needs.build-variable.outputs.artifact-name }}
    - name: Download workspace and tv fonts
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.cut-instances.outputs.workspace-artifact-name }}
        path: ${{ needs.cut-instances.outputs.workspace-artifact-name }}
    - name: Download Android font
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.cut-instances.outputs.android-artifact-name }}
        path: ${{ needs.cut-instances.outputs.android-artifact-name }}
    - name: Create release archives
      id: release-archives
      run: |
        # Note: unsupported characters (such as spaces) are changes for periods
        #       when uploading to the release
        variable_zip_name="GoogleSansFlex-${GITHUB_REF#refs/*/}.zip"
        echo "variable-zip-name=$variable_zip_name" >> "$GITHUB_OUTPUT"
        cd "$GITHUB_WORKSPACE/${{ needs.build-variable.outputs.artifact-name }}" \
          && zip -9 "../$variable_zip_name" *.ttf

        workspace_zip_name="GoogleSansFlex-${GITHUB_REF#refs/*/} workspace.zip"
        echo "workspace-zip-name=$workspace_zip_name" >> "$GITHUB_OUTPUT"
        cd "$GITHUB_WORKSPACE/${{ needs.cut-instances.outputs.workspace-artifact-name }}/workspace" \
          && zip -9 "../../$workspace_zip_name" *.ttf *.md

        tv_zip_name="GoogleSansFlex-${GITHUB_REF#refs/*/} tv.zip"
        echo "tv-zip-name=$tv_zip_name" >> "$GITHUB_OUTPUT"
        cd "$GITHUB_WORKSPACE/${{ needs.cut-instances.outputs.workspace-artifact-name }}/tv" \
          && zip -9 "../../$tv_zip_name" *.ttf *.md
        
        android_zip_name="GoogleSansFlex-${GITHUB_REF#refs/*/} Android.zip"
        echo "android-zip-name=$android_zip_name" >> "$GITHUB_OUTPUT"
        cd "$GITHUB_WORKSPACE/${{ needs.cut-instances.outputs.android-artifact-name }}"
        # Rename file to match what Android's already using (regardless as to how representative the name is)
        mv GoogleSansFlex[GRAD,ROND,opsz,slnt,wdth,wght].ttf GoogleSansFlex-Regular.ttf
        zip -9 "../$android_zip_name" *.ttf *.md
    - name: Upload variable font archive to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ${{ steps.release-archives.outputs.variable-zip-name }}
        overwrite: true
        body: "Production ready fonts"
    - name: Upload workspace fonts archive to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ${{ steps.release-archives.outputs.workspace-zip-name }}
    - name: Upload Android font archive to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ${{ steps.release-archives.outputs.android-zip-name }}
    - name: Upload tv font archive to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ${{ steps.release-archives.outputs.tv-zip-name }}
