name: Release variable & workspace fonts

on:
  release:
    # A release, pre-release, or draft of a release was published
    types: [published]

jobs:
  build-variable:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Checkout ${{ github.ref_name }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ./.github/workflows/python-version.txt
        cache: pip
    - name: Build font
      id: build-ufos
      uses: ./.github/actions/build-ufos-py
    outputs:
      artifact-name: ${{ steps.build-ufos.outputs.artifact-name }}
  cut-instances:
    needs:
    - build-variable
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Checkout ${{ github.ref_name }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ./.github/workflows/python-version.txt
        cache: pip
    - name: Download artifact files
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build-variable.outputs.artifact-name }}
        path: fonts/variable
    - name: Set up venv
      run: make venv
    - name: Cut instances
      run: |
        touch build.stamp # don't rebuild fonts
        . venv/bin/activate && make release
        # Copy README_WORKSPACE.md into the target folder with the fonts
        cp README_WORKSPACE.md fonts/workspace/
    - name: Generate archive name
      id: zip-name
      uses: alpha-tango-kilo/gha-artifact-name@v1
      with:
        repo-name: Google Sans Flex
        overrides: "release: workspace"
    - name: Upload archive
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.zip-name.outputs.artifact-name }}
        path: fonts/workspace
        compression-level: 9
        if-no-files-found: error
    outputs:
      artifact-name: ${{ steps.zip-name.outputs.artifact-name }}
  test-variable:
    needs:
    - build-variable
    uses: daltonmaag/googlesans-flex-playground/.github/workflows/tests.yml@main
    with:
      branch: ${{ github.ref_name }}
      artifact-name: ${{ needs.build-variable.outputs.artifact-name }}
  test-workspace:
    needs:
    - cut-instances
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Checkout ${{ github.ref_name }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ./.github/workflows/python-version.txt
        cache: pip
    - name: Download workspace fonts
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.cut-instances.outputs.artifact-name }}
        path: fonts/workspace
    - name: Run Fontbakery
      id: fontbakery-workspace
      env:
        SKIP_SOURCES: 1
      run: scripts/fontbakery.sh
    - name: Upload Fontbakery reports
      uses: actions/upload-artifact@v4
      # Always upload reports (even during a pipeline fail), so long as Fontbakery completed
      # https://docs.github.com/en/actions/learn-github-actions/expressions#always
      # https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context
      if: ${{ !cancelled() && (steps.fontbakery-workspace.conclusion == 'success' || steps.fontbakery-workspace.conclusion == 'failure') }}
      with:
        name: Fontbakery workspace reports
        path: out/fontbakery
        if-no-files-found: error
  upload-to-release:
    needs:
    - build-variable
    - cut-instances
    - test-variable
    - test-workspace
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Download variable fonts
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build-variable.outputs.artifact-name }}
        path: ${{ needs.build-variable.outputs.artifact-name }}
    - name: Download workspace fonts
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.cut-instances.outputs.artifact-name }}
        path: ${{ needs.cut-instances.outputs.artifact-name }}
    - name: Create release archives
      id: release-archives
      run: |
        # Note: unsupported characters (such as spaces) are changes for periods
        #       when uploading to the release
        variable_zip_name="GoogleSansFlex-${GITHUB_REF#refs/*/}.zip"
        echo "variable-zip-name=$variable_zip_name" >> "$GITHUB_OUTPUT"
        cd "$GITHUB_WORKSPACE/${{ needs.build-variable.outputs.artifact-name }}" \
          && zip -9 "../$variable_zip_name" *.ttf

        workspace_zip_name="GoogleSansFlex-${GITHUB_REF#refs/*/} workspace.zip"
        echo "workspace-zip-name=$workspace_zip_name" >> "$GITHUB_OUTPUT"
        cd "$GITHUB_WORKSPACE/${{ needs.cut-instances.outputs.artifact-name }}" \
          && zip -9 "../$workspace_zip_name" *.ttf *.md
    - name: Upload variable font archive to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ${{ steps.release-archives.outputs.variable-zip-name }}
        overwrite: true
        body: "Production ready fonts"
    - name: Upload workspace fonts archive to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ${{ steps.release-archives.outputs.workspace-zip-name }}
